--------------------------------------------------------
--  Constraints for Table ETX_WEB_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_ATTACHMENT" ADD CONSTRAINT "PK_ATT_ID" PRIMARY KEY ("ATT_ID")
/
  ALTER TABLE "ETX_WEB_ATTACHMENT" MODIFY ("ATT_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_BUSINESS
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_BUSINESS" MODIFY ("BUS_ACTIVE_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS" MODIFY ("BUS_CREATED_ON" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS" MODIFY ("BUS_CREATED_BY" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS" MODIFY ("BUS_NAME" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS" MODIFY ("BUS_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS" ADD CONSTRAINT "PK_BUS_ID" PRIMARY KEY ("BUS_ID")
/


--------------------------------------------------------
--  Constraints for Table ETX_WEB_BUSINESS_USER_CONFIG
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" ADD CONSTRAINT "PK_BUC_ID" PRIMARY KEY ("BUC_ID")
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUC_ACTIVE_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUC_CREATED_ON" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUC_CREATED_BY" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUC_NOTIFICATIONS_ENABLED" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUC_NAME" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUS_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("USR_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" MODIFY ("BUC_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_CONFIG
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_CONFIG" ADD CONSTRAINT "PK_CFG_ID" PRIMARY KEY ("CFG_ID")
/
  ALTER TABLE "ETX_WEB_CONFIG" MODIFY ("CFG_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_LABEL_TRANSLATION
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_LABEL_TRANSLATION" ADD CONSTRAINT "PK_LTR_ID" PRIMARY KEY ("LTR_ID")
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_LANG
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_LANG" ADD CONSTRAINT "PK_LNG_ID" PRIMARY KEY ("LNG_ID")
/
  ALTER TABLE "ETX_WEB_LANG" MODIFY ("LNG_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_MESSAGE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_MESSAGE" MODIFY ("MSG_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE" ADD CONSTRAINT "PK_MSG_ID" PRIMARY KEY ("MSG_ID")
/
  ALTER TABLE "ETX_WEB_MESSAGE" MODIFY ("MSG_REMOTE_PARTY_NAME" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE" MODIFY ("MSG_LOCAL_PARTY_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE" MODIFY ("MSG_ACTIVE_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE" MODIFY ("MSG_CREATED_ON" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_MESSAGE_READ
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_MESSAGE_READ" ADD CONSTRAINT "PK_MSR_ID" PRIMARY KEY ("MSR_ID")
/
  ALTER TABLE "ETX_WEB_MESSAGE_READ" MODIFY ("MSR_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_METADATA
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_METADATA" MODIFY ("MTD_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_METADATA" ADD CONSTRAINT "PK_MTD_ID" PRIMARY KEY ("MTD_ID")
/
  ALTER TABLE "ETX_WEB_METADATA" MODIFY ("MTD_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_NOTIFICATION" ADD PRIMARY KEY ("NTF_ID")
/
  ALTER TABLE "ETX_WEB_NOTIFICATION" MODIFY ("NTF_CREATED_ON" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_NOTIFICATION" MODIFY ("NTF_ID" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_PARTY
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_ACTIVE_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_NOTIFICATIONS_ENABLED" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_CREATED_ON" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_CREATED_BY" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" ADD CONSTRAINT "PK_PAR_ID" PRIMARY KEY ("PAR_ID")
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("BUS_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_DISPLAY_NAME" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" ADD UNIQUE ("PAR_NODE_NAME")
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_NODE_NAME" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_NODE_PASS" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PARTY" MODIFY ("PAR_NODE_USR" NOT NULL ENABLE)
/
--------------------------------------------------------
--  Constraints for Table ETX_WEB_PRIVILEGE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_PRIVILEGE" MODIFY ("PRV_TYPE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PRIVILEGE" MODIFY ("PRV_NAME" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_PRIVILEGE" ADD CONSTRAINT "PK_PRV_TYPE" PRIMARY KEY ("PRV_TYPE")
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_ROLE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_ROLE" ADD CONSTRAINT "PK_ROL_TYPE" PRIMARY KEY ("ROL_TYPE")
/
  ALTER TABLE "ETX_WEB_ROLE" MODIFY ("ROL_SCOPE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_ROLE" MODIFY ("ROL_TYPE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_ROLE" MODIFY ("ROL_NAME" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_ROLE_PRIVILEGE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_ROLE_PRIVILEGE" MODIFY ("PRV_TYPE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_ROLE_PRIVILEGE" MODIFY ("ROL_TYPE" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_USER
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_USER" MODIFY ("USR_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER" ADD CONSTRAINT "PK_USR_ID" PRIMARY KEY ("USR_ID")
/
  ALTER TABLE "ETX_WEB_USER" MODIFY ("USR_LOGIN" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER" MODIFY ("USR_ACTIVE_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER" MODIFY ("USR_CREATED_ON" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER" MODIFY ("USR_CREATED_BY" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_USER_ROLE" MODIFY ("URO_ACTIVE_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER_ROLE" MODIFY ("URO_CREATED_ON" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER_ROLE" MODIFY ("URO_CREATED_BY" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER_ROLE" MODIFY ("ROL_TYPE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER_ROLE" MODIFY ("USR_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER_ROLE" MODIFY ("URO_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_USER_ROLE" ADD CONSTRAINT "PK_URO_ID" PRIMARY KEY ("URO_ID")
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_ATTACHMENT
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_ATTACHMENT" ADD CONSTRAINT "FK_ATT_MSG_ID" FOREIGN KEY ("MSG_ID")
	  REFERENCES "ETX_WEB_MESSAGE" ("MSG_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_BUSINESS_USER_CONFIG
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" ADD CONSTRAINT "ETX_WEB_BUC_FK_BUSINESS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "ETX_WEB_BUSINESS" ("BUS_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_BUSINESS_USER_CONFIG" ADD CONSTRAINT "ETX_WEB_BUC_FK_USER" FOREIGN KEY ("USR_ID")
	  REFERENCES "ETX_WEB_USER" ("USR_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_LABEL_TRANSLATION
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_LABEL_TRANSLATION" ADD CONSTRAINT "FK_LTR_LNG_ID" FOREIGN KEY ("LNG_ID")
	  REFERENCES "ETX_WEB_LANG" ("LNG_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_MESSAGE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_MESSAGE" ADD CONSTRAINT "ETX_WEB_MESSAGE_FK_PARTY" FOREIGN KEY ("MSG_LOCAL_PARTY_ID")
	  REFERENCES "ETX_WEB_PARTY" ("PAR_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_MESSAGE_READ
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_MESSAGE_READ" ADD CONSTRAINT "FK_MSR_MSG_ID" FOREIGN KEY ("MSG_ID")
	  REFERENCES "ETX_WEB_MESSAGE" ("MSG_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_MESSAGE_READ" ADD CONSTRAINT "FK_MSR_USR_ID" FOREIGN KEY ("USR_ID")
	  REFERENCES "ETX_WEB_USER" ("USR_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_METADATA
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_METADATA" ADD CONSTRAINT "FK_MTD_MSG_ID" FOREIGN KEY ("MSG_ID")
	  REFERENCES "ETX_WEB_MESSAGE" ("MSG_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_FK_MESSAGE" FOREIGN KEY ("MSG_ID")
	  REFERENCES "ETX_WEB_MESSAGE" ("MSG_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_FK_PARTY" FOREIGN KEY ("PAR_ID")
	  REFERENCES "ETX_WEB_PARTY" ("PAR_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_NOTIFICATION" ADD CONSTRAINT "NOTIFICATION_FK_BUC" FOREIGN KEY ("BUC_ID")
	  REFERENCES "ETX_WEB_BUSINESS_USER_CONFIG" ("BUC_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_PARTY
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_PARTY" ADD CONSTRAINT "ETX_WEB_PARTY_FK_BUSINESS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "ETX_WEB_BUSINESS" ("BUS_ID") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_ROLE_PRIVILEGE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_ROLE_PRIVILEGE" ADD CONSTRAINT "ETX_WEB_ROLE_PRV_FK_PRV" FOREIGN KEY ("PRV_TYPE")
	  REFERENCES "ETX_WEB_PRIVILEGE" ("PRV_TYPE") ENABLE
/
  ALTER TABLE "ETX_WEB_ROLE_PRIVILEGE" ADD CONSTRAINT "ETX_WEB_ROLE_PRV_FK_ROLE" FOREIGN KEY ("ROL_TYPE")
	  REFERENCES "ETX_WEB_ROLE" ("ROL_TYPE") ENABLE
/

--------------------------------------------------------
--  Ref Constraints for Table ETX_WEB_USER_ROLE
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_USER_ROLE" ADD CONSTRAINT "ETX_WEB_USER_ROLE_FK_BUSINESS" FOREIGN KEY ("BUS_ID")
	  REFERENCES "ETX_WEB_BUSINESS" ("BUS_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_USER_ROLE" ADD CONSTRAINT "ETX_WEB_USER_ROLE_FK_PARTY" FOREIGN KEY ("PAR_ID")
	  REFERENCES "ETX_WEB_PARTY" ("PAR_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_USER_ROLE" ADD CONSTRAINT "ETX_WEB_USER_ROLE_FK_ROLE" FOREIGN KEY ("ROL_TYPE")
	  REFERENCES "ETX_WEB_ROLE" ("ROL_TYPE") ENABLE
/
  ALTER TABLE "ETX_WEB_USER_ROLE" ADD CONSTRAINT "ETX_WEB_USER_ROLE_FK_USER" FOREIGN KEY ("USR_ID")
	  REFERENCES "ETX_WEB_USER" ("USR_ID") ENABLE
/


--------------------------------------------------------
--  Constraints for Table ETX_WEB_MESSAGE_STATUS
--------------------------------------------------------

  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" MODIFY ("MST_ID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" ADD CONSTRAINT "PK_MST_ID" PRIMARY KEY ("MST_ID")
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" ADD CONSTRAINT "ETX_WEB_MESSAGE_STATUS_FK_MSG" FOREIGN KEY ("MSG_ID")
	  REFERENCES "ETX_WEB_MESSAGE" ("MSG_ID") ENABLE
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" MODIFY ("MST_UUID" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" MODIFY ("MST_STATE" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" MODIFY ("MST_STATUS" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" MODIFY ("MST_LOGIN" NOT NULL ENABLE)
/
  ALTER TABLE "ETX_WEB_MESSAGE_STATUS" MODIFY ("MST_CREATED_ON" NOT NULL ENABLE)
/

--------------------------------------------------------
--  Constraints for Table ETX_WEB_BUSINESS_CONFIG
--------------------------------------------------------

ALTER TABLE "ETX_WEB_BUSINESS_CONFIG" ADD CONSTRAINT "PK_BCG_ID" PRIMARY KEY ("BCG_ID")
/
ALTER TABLE "ETX_WEB_BUSINESS_CONFIG" MODIFY ("BCG_ID" NOT NULL ENABLE)
/
ALTER TABLE "ETX_WEB_BUSINESS_CONFIG" MODIFY ("BUS_ID" NOT NULL ENABLE)
/
ALTER TABLE "ETX_WEB_BUSINESS_CONFIG" ADD CONSTRAINT "ETX_WEB_BCG_ID_FK" FOREIGN KEY ("BUS_ID")
	  REFERENCES "ETX_WEB_BUSINESS" ("BUS_ID")
/
ALTER TABLE "ETX_WEB_BUSINESS_CONFIG" ADD CONSTRAINT "ETX_WEB_BCG_ID_NAME" UNIQUE ("BUS_ID", "BCG_PROPERTY_NAME")
/
--------------------------------------------------------
--  DDL for Trigger TRG_A_IU_USER_ROLE
--------------------------------------------------------
CREATE TRIGGER TRG_A_IU_USER_ROLE AFTER INSERT OR UPDATE ON ETX_WEB_USER_ROLE
FOR EACH ROW
DECLARE
V_ROLE ETX_WEB_ROLE%ROWTYPE;
INVALID_USER_ROLE_EXCEPTION EXCEPTION;
BEGIN
SELECT * INTO V_ROLE FROM ETX_WEB_ROLE WHERE ROL_TYPE = :NEW.ROL_TYPE;
CASE V_ROLE.ROL_SCOPE
 WHEN 'PARTY_SCOPE' THEN
   IF :NEW.PAR_ID IS NULL OR :NEW.BUS_ID IS NOT NULL THEN
     RAISE INVALID_USER_ROLE_EXCEPTION;
   END IF;
 WHEN 'BUSINESS_SCOPE' THEN
   IF :NEW.PAR_ID IS NOT NULL OR :NEW.BUS_ID IS NULL THEN
     RAISE INVALID_USER_ROLE_EXCEPTION;
   END IF;
 WHEN 'SYSTEM_SCOPE' THEN
   IF :NEW.PAR_ID IS NOT NULL OR :NEW.BUS_ID IS NOT NULL THEN
     RAISE INVALID_USER_ROLE_EXCEPTION;
   END IF;
 ELSE
   RAISE INVALID_USER_ROLE_EXCEPTION;
END CASE;
END;
/