//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * 
 * 				Extension for a manifestation.
 * 			
 * 
 * <p>Java class for ManifestationExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManifestationExtensionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_manifestation_extension_base">
 *       &lt;sequence>
 *         &lt;element name="last_sequence" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManifestationExtensionType", namespace = "urn:eu:ec:cm:common:extensions:v11", propOrder = {
    "lastSequence"
})
public class ManifestationExtensionType
    extends TManifestationExtensionBase
{

    @XmlElement(name = "last_sequence", required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger lastSequence;

    /**
     * Gets the value of the lastSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLastSequence() {
        return lastSequence;
    }

    /**
     * Sets the value of the lastSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLastSequence(BigInteger value) {
        this.lastSequence = value;
    }

}
