//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.ec.etrustex.metadata.egreffe package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EcTransmissionRequest_QNAME = new QName("urn:eu:ec:transmission:v11", "ec_transmission_request");
    private final static QName _Work_QNAME = new QName("http://publications.europa.eu/resource/core-metadata", "work");
    private final static QName _ProcedureInterinstitutional_QNAME = new QName("http://publications.europa.eu/resource/core-metadata", "procedure_interinstitutional");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.ec.etrustex.metadata.egreffe
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AgentListType }
     * 
     */
    public AgentListType createAgentListType() {
        return new AgentListType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link TAgentEvent }
     * 
     */
    public TAgentEvent createTAgentEvent() {
        return new TAgentEvent();
    }

    /**
     * Create an instance of {@link TClassificationSummary }
     * 
     */
    public TClassificationSummary createTClassificationSummary() {
        return new TClassificationSummary();
    }

    /**
     * Create an instance of {@link TWorkPropReg }
     * 
     */
    public TWorkPropReg createTWorkPropReg() {
        return new TWorkPropReg();
    }

    /**
     * Create an instance of {@link TDescriptionSummary }
     * 
     */
    public TDescriptionSummary createTDescriptionSummary() {
        return new TDescriptionSummary();
    }

    /**
     * Create an instance of {@link DelegationType }
     * 
     */
    public DelegationType createDelegationType() {
        return new DelegationType();
    }

    /**
     * Create an instance of {@link TransmissionExtensionBaseType }
     * 
     */
    public TransmissionExtensionBaseType createTransmissionExtensionBaseType() {
        return new TransmissionExtensionBaseType();
    }

    /**
     * Create an instance of {@link SecurityInfoType }
     * 
     */
    public SecurityInfoType createSecurityInfoType() {
        return new SecurityInfoType();
    }

    /**
     * Create an instance of {@link SecurableConstantType }
     * 
     */
    public SecurableConstantType createSecurableConstantType() {
        return new SecurableConstantType();
    }

    /**
     * Create an instance of {@link TWork }
     * 
     */
    public TWork createTWork() {
        return new TWork();
    }

    /**
     * Create an instance of {@link TClassificationDirectory }
     * 
     */
    public TClassificationDirectory createTClassificationDirectory() {
        return new TClassificationDirectory();
    }

    /**
     * Create an instance of {@link TransmissionRequestExtensionBaseType }
     * 
     */
    public TransmissionRequestExtensionBaseType createTransmissionRequestExtensionBaseType() {
        return new TransmissionRequestExtensionBaseType();
    }

    /**
     * Create an instance of {@link TransmissionExtensionType }
     * 
     */
    public TransmissionExtensionType createTransmissionExtensionType() {
        return new TransmissionExtensionType();
    }

    /**
     * Create an instance of {@link WorkflowNumberType }
     * 
     */
    public WorkflowNumberType createWorkflowNumberType() {
        return new WorkflowNumberType();
    }

    /**
     * Create an instance of {@link WorkflowExtensionBaseType }
     * 
     */
    public WorkflowExtensionBaseType createWorkflowExtensionBaseType() {
        return new WorkflowExtensionBaseType();
    }

    /**
     * Create an instance of {@link TDurability }
     * 
     */
    public TDurability createTDurability() {
        return new TDurability();
    }

    /**
     * Create an instance of {@link TIdActBasicSummarized }
     * 
     */
    public TIdActBasicSummarized createTIdActBasicSummarized() {
        return new TIdActBasicSummarized();
    }

    /**
     * Create an instance of {@link TClassificationsDirectory }
     * 
     */
    public TClassificationsDirectory createTClassificationsDirectory() {
        return new TClassificationsDirectory();
    }

    /**
     * Create an instance of {@link TIdentifierProcedure.NumberProcedure }
     * 
     */
    public TIdentifierProcedure.NumberProcedure createTIdentifierProcedureNumberProcedure() {
        return new TIdentifierProcedure.NumberProcedure();
    }

    /**
     * Create an instance of {@link LegalBasisListType }
     * 
     */
    public LegalBasisListType createLegalBasisListType() {
        return new LegalBasisListType();
    }

    /**
     * Create an instance of {@link TIdActBasicSummarizedCelex }
     * 
     */
    public TIdActBasicSummarizedCelex createTIdActBasicSummarizedCelex() {
        return new TIdActBasicSummarizedCelex();
    }

    /**
     * Create an instance of {@link TTitle }
     * 
     */
    public TTitle createTTitle() {
        return new TTitle();
    }

    /**
     * Create an instance of {@link TWorkCc }
     * 
     */
    public TWorkCc createTWorkCc() {
        return new TWorkCc();
    }

    /**
     * Create an instance of {@link TIdDocRelated }
     * 
     */
    public TIdDocRelated createTIdDocRelated() {
        return new TIdDocRelated();
    }

    /**
     * Create an instance of {@link TPartOfWork }
     * 
     */
    public TPartOfWork createTPartOfWork() {
        return new TPartOfWork();
    }

    /**
     * Create an instance of {@link CommentType }
     * 
     */
    public CommentType createCommentType() {
        return new CommentType();
    }

    /**
     * Create an instance of {@link TProcedureInterinstitutional }
     * 
     */
    public TProcedureInterinstitutional createTProcedureInterinstitutional() {
        return new TProcedureInterinstitutional();
    }

    /**
     * Create an instance of {@link ContactDetailsType }
     * 
     */
    public ContactDetailsType createContactDetailsType() {
        return new ContactDetailsType();
    }

    /**
     * Create an instance of {@link TWork.TypeWork }
     * 
     */
    public TWork.TypeWork createTWorkTypeWork() {
        return new TWork.TypeWork();
    }

    /**
     * Create an instance of {@link TProcedureExtensionBase }
     * 
     */
    public TProcedureExtensionBase createTProcedureExtensionBase() {
        return new TProcedureExtensionBase();
    }

    /**
     * Create an instance of {@link TWork.VersionWork }
     * 
     */
    public TWork.VersionWork createTWorkVersionWork() {
        return new TWork.VersionWork();
    }

    /**
     * Create an instance of {@link TDecision }
     * 
     */
    public TDecision createTDecision() {
        return new TDecision();
    }

    /**
     * Create an instance of {@link TWork.IdentifierWork }
     * 
     */
    public TWork.IdentifierWork createTWorkIdentifierWork() {
        return new TWork.IdentifierWork();
    }

    /**
     * Create an instance of {@link TIdActModifierSummarizedCelex }
     * 
     */
    public TIdActModifierSummarizedCelex createTIdActModifierSummarizedCelex() {
        return new TIdActModifierSummarizedCelex();
    }

    /**
     * Create an instance of {@link TIdentifierProcedure.ProcId }
     * 
     */
    public TIdentifierProcedure.ProcId createTIdentifierProcedureProcId() {
        return new TIdentifierProcedure.ProcId();
    }

    /**
     * Create an instance of {@link TReferenceManifestation }
     * 
     */
    public TReferenceManifestation createTReferenceManifestation() {
        return new TReferenceManifestation();
    }

    /**
     * Create an instance of {@link TEventExtension }
     * 
     */
    public TEventExtension createTEventExtension() {
        return new TEventExtension();
    }

    /**
     * Create an instance of {@link NumberType }
     * 
     */
    public NumberType createNumberType() {
        return new NumberType();
    }

    /**
     * Create an instance of {@link TWorkRef }
     * 
     */
    public TWorkRef createTWorkRef() {
        return new TWorkRef();
    }

    /**
     * Create an instance of {@link TIdentifierProcedure.YearProcedure }
     * 
     */
    public TIdentifierProcedure.YearProcedure createTIdentifierProcedureYearProcedure() {
        return new TIdentifierProcedure.YearProcedure();
    }

    /**
     * Create an instance of {@link TIdActModifierSummarized }
     * 
     */
    public TIdActModifierSummarized createTIdActModifierSummarized() {
        return new TIdActModifierSummarized();
    }

    /**
     * Create an instance of {@link AgentType }
     * 
     */
    public AgentType createAgentType() {
        return new AgentType();
    }

    /**
     * Create an instance of {@link TAgentWork }
     * 
     */
    public TAgentWork createTAgentWork() {
        return new TAgentWork();
    }

    /**
     * Create an instance of {@link TWork.DateWork }
     * 
     */
    public TWork.DateWork createTWorkDateWork() {
        return new TWork.DateWork();
    }

    /**
     * Create an instance of {@link TNumberParts }
     * 
     */
    public TNumberParts createTNumberParts() {
        return new TNumberParts();
    }

    /**
     * Create an instance of {@link TExpressionLegisSum }
     * 
     */
    public TExpressionLegisSum createTExpressionLegisSum() {
        return new TExpressionLegisSum();
    }

    /**
     * Create an instance of {@link TWorkExtensionBase }
     * 
     */
    public TWorkExtensionBase createTWorkExtensionBase() {
        return new TWorkExtensionBase();
    }

    /**
     * Create an instance of {@link TExpression }
     * 
     */
    public TExpression createTExpression() {
        return new TExpression();
    }

    /**
     * Create an instance of {@link TAgentPerson }
     * 
     */
    public TAgentPerson createTAgentPerson() {
        return new TAgentPerson();
    }

    /**
     * Create an instance of {@link TEventLegal }
     * 
     */
    public TEventLegal createTEventLegal() {
        return new TEventLegal();
    }

    /**
     * Create an instance of {@link TEventExtensionBase }
     * 
     */
    public TEventExtensionBase createTEventExtensionBase() {
        return new TEventExtensionBase();
    }

    /**
     * Create an instance of {@link TManifestationExtensionBase }
     * 
     */
    public TManifestationExtensionBase createTManifestationExtensionBase() {
        return new TManifestationExtensionBase();
    }

    /**
     * Create an instance of {@link TLegalProcedure }
     * 
     */
    public TLegalProcedure createTLegalProcedure() {
        return new TLegalProcedure();
    }

    /**
     * Create an instance of {@link TEventLegal.TypeInterinstitutionalprocedure }
     * 
     */
    public TEventLegal.TypeInterinstitutionalprocedure createTEventLegalTypeInterinstitutionalprocedure() {
        return new TEventLegal.TypeInterinstitutionalprocedure();
    }

    /**
     * Create an instance of {@link YearType }
     * 
     */
    public YearType createYearType() {
        return new YearType();
    }

    /**
     * Create an instance of {@link TIdentifierWorkAlternative }
     * 
     */
    public TIdentifierWorkAlternative createTIdentifierWorkAlternative() {
        return new TIdentifierWorkAlternative();
    }

    /**
     * Create an instance of {@link TSequencePart }
     * 
     */
    public TSequencePart createTSequencePart() {
        return new TSequencePart();
    }

    /**
     * Create an instance of {@link WorkflowType }
     * 
     */
    public WorkflowType createWorkflowType() {
        return new WorkflowType();
    }

    /**
     * Create an instance of {@link ExpressionExtensionType }
     * 
     */
    public ExpressionExtensionType createExpressionExtensionType() {
        return new ExpressionExtensionType();
    }

    /**
     * Create an instance of {@link TDocumentLegal }
     * 
     */
    public TDocumentLegal createTDocumentLegal() {
        return new TDocumentLegal();
    }

    /**
     * Create an instance of {@link WorkExtensionType }
     * 
     */
    public WorkExtensionType createWorkExtensionType() {
        return new WorkExtensionType();
    }

    /**
     * Create an instance of {@link WorkflowExtensionType }
     * 
     */
    public WorkflowExtensionType createWorkflowExtensionType() {
        return new WorkflowExtensionType();
    }

    /**
     * Create an instance of {@link TIdentifierProcedure }
     * 
     */
    public TIdentifierProcedure createTIdentifierProcedure() {
        return new TIdentifierProcedure();
    }

    /**
     * Create an instance of {@link AgentPersonNameListType }
     * 
     */
    public AgentPersonNameListType createAgentPersonNameListType() {
        return new AgentPersonNameListType();
    }

    /**
     * Create an instance of {@link TDescriptorsEv }
     * 
     */
    public TDescriptorsEv createTDescriptorsEv() {
        return new TDescriptorsEv();
    }

    /**
     * Create an instance of {@link TransmissionRequestType }
     * 
     */
    public TransmissionRequestType createTransmissionRequestType() {
        return new TransmissionRequestType();
    }

    /**
     * Create an instance of {@link WorkNumberType }
     * 
     */
    public WorkNumberType createWorkNumberType() {
        return new WorkNumberType();
    }

    /**
     * Create an instance of {@link TClassificationsSummary }
     * 
     */
    public TClassificationsSummary createTClassificationsSummary() {
        return new TClassificationsSummary();
    }

    /**
     * Create an instance of {@link TObsolete }
     * 
     */
    public TObsolete createTObsolete() {
        return new TObsolete();
    }

    /**
     * Create an instance of {@link TPlaceAdoption }
     * 
     */
    public TPlaceAdoption createTPlaceAdoption() {
        return new TPlaceAdoption();
    }

    /**
     * Create an instance of {@link TEventLegal.TypeEvent }
     * 
     */
    public TEventLegal.TypeEvent createTEventLegalTypeEvent() {
        return new TEventLegal.TypeEvent();
    }

    /**
     * Create an instance of {@link TWorkOpiCor }
     * 
     */
    public TWorkOpiCor createTWorkOpiCor() {
        return new TWorkOpiCor();
    }

    /**
     * Create an instance of {@link TWorkLegisSum }
     * 
     */
    public TWorkLegisSum createTWorkLegisSum() {
        return new TWorkLegisSum();
    }

    /**
     * Create an instance of {@link TYesno }
     * 
     */
    public TYesno createTYesno() {
        return new TYesno();
    }

    /**
     * Create an instance of {@link TIdentifierEgreffe }
     * 
     */
    public TIdentifierEgreffe createTIdentifierEgreffe() {
        return new TIdentifierEgreffe();
    }

    /**
     * Create an instance of {@link SubsidiarityProportionalityApplicationType }
     * 
     */
    public SubsidiarityProportionalityApplicationType createSubsidiarityProportionalityApplicationType() {
        return new SubsidiarityProportionalityApplicationType();
    }

    /**
     * Create an instance of {@link TDateInitial }
     * 
     */
    public TDateInitial createTDateInitial() {
        return new TDateInitial();
    }

    /**
     * Create an instance of {@link TEventLegal.DateEvent }
     * 
     */
    public TEventLegal.DateEvent createTEventLegalDateEvent() {
        return new TEventLegal.DateEvent();
    }

    /**
     * Create an instance of {@link ManifestationExtensionType }
     * 
     */
    public ManifestationExtensionType createManifestationExtensionType() {
        return new ManifestationExtensionType();
    }

    /**
     * Create an instance of {@link AgentPersonNameType }
     * 
     */
    public AgentPersonNameType createAgentPersonNameType() {
        return new AgentPersonNameType();
    }

    /**
     * Create an instance of {@link EventExtensionType }
     * 
     */
    public EventExtensionType createEventExtensionType() {
        return new EventExtensionType();
    }

    /**
     * Create an instance of {@link TLanguageDraft }
     * 
     */
    public TLanguageDraft createTLanguageDraft() {
        return new TLanguageDraft();
    }

    /**
     * Create an instance of {@link TExpressionExtensionBase }
     * 
     */
    public TExpressionExtensionBase createTExpressionExtensionBase() {
        return new TExpressionExtensionBase();
    }

    /**
     * Create an instance of {@link TExpression.Language }
     * 
     */
    public TExpression.Language createTExpressionLanguage() {
        return new TExpression.Language();
    }

    /**
     * Create an instance of {@link ContactType }
     * 
     */
    public ContactType createContactType() {
        return new ContactType();
    }

    /**
     * Create an instance of {@link TModeDecision }
     * 
     */
    public TModeDecision createTModeDecision() {
        return new TModeDecision();
    }

    /**
     * Create an instance of {@link GenericIdentificationNumberType }
     * 
     */
    public GenericIdentificationNumberType createGenericIdentificationNumberType() {
        return new GenericIdentificationNumberType();
    }

    /**
     * Create an instance of {@link TWorkLayer0 }
     * 
     */
    public TWorkLayer0 createTWorkLayer0() {
        return new TWorkLayer0();
    }

    /**
     * Create an instance of {@link ProcedureExtensionType }
     * 
     */
    public ProcedureExtensionType createProcedureExtensionType() {
        return new ProcedureExtensionType();
    }

    /**
     * Create an instance of {@link TIdActConsolidatedSummarizedCelex }
     * 
     */
    public TIdActConsolidatedSummarizedCelex createTIdActConsolidatedSummarizedCelex() {
        return new TIdActConsolidatedSummarizedCelex();
    }

    /**
     * Create an instance of {@link TNumberProcedureInternal }
     * 
     */
    public TNumberProcedureInternal createTNumberProcedureInternal() {
        return new TNumberProcedureInternal();
    }

    /**
     * Create an instance of {@link TDescriptorEv }
     * 
     */
    public TDescriptorEv createTDescriptorEv() {
        return new TDescriptorEv();
    }

    /**
     * Create an instance of {@link TManifestation }
     * 
     */
    public TManifestation createTManifestation() {
        return new TManifestation();
    }

    /**
     * Create an instance of {@link TransmissionType }
     * 
     */
    public TransmissionType createTransmissionType() {
        return new TransmissionType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransmissionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:eu:ec:transmission:v11", name = "ec_transmission_request")
    public JAXBElement<TransmissionRequestType> createEcTransmissionRequest(TransmissionRequestType value) {
        return new JAXBElement<>(_EcTransmissionRequest_QNAME, TransmissionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TWork }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://publications.europa.eu/resource/core-metadata", name = "work")
    public JAXBElement<TWork> createWork(TWork value) {
        return new JAXBElement<>(_Work_QNAME, TWork.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TProcedureInterinstitutional }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://publications.europa.eu/resource/core-metadata", name = "procedure_interinstitutional")
    public JAXBElement<TProcedureInterinstitutional> createProcedureInterinstitutional(TProcedureInterinstitutional value) {
        return new JAXBElement<>(_ProcedureInterinstitutional_QNAME, TProcedureInterinstitutional.class, null, value);
    }

}
