//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Extension for a procedure.
 * 			
 * 
 * <p>Java class for ProcedureExtensionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcedureExtensionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_procedure_extension_base">
 *       &lt;sequence>
 *         &lt;element name="subsidiarity_proportionality_application" type="{urn:eu:ec:cm:common:extensions:v11}SubsidiarityProportionalityApplicationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcedureExtensionType", namespace = "urn:eu:ec:cm:common:extensions:v11", propOrder = {
    "subsidiarityProportionalityApplication"
})
public class ProcedureExtensionType
    extends TProcedureExtensionBase
{

    @XmlElement(name = "subsidiarity_proportionality_application")
    protected SubsidiarityProportionalityApplicationType subsidiarityProportionalityApplication;

    /**
     * Gets the value of the subsidiarityProportionalityApplication property.
     * 
     * @return
     *     possible object is
     *     {@link SubsidiarityProportionalityApplicationType }
     *     
     */
    public SubsidiarityProportionalityApplicationType getSubsidiarityProportionalityApplication() {
        return subsidiarityProportionalityApplication;
    }

    /**
     * Sets the value of the subsidiarityProportionalityApplication property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubsidiarityProportionalityApplicationType }
     *     
     */
    public void setSubsidiarityProportionalityApplication(SubsidiarityProportionalityApplicationType value) {
        this.subsidiarityProportionalityApplication = value;
    }

}
