//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for t_event_legal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_event_legal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type_event">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://publications.europa.eu/resource/events/>t_event">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="date_event">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="agent_event" type="{http://publications.europa.eu/resource/core-metadata}t_agent_event" maxOccurs="unbounded"/>
 *         &lt;element name="type_interinstitutionalprocedure">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://publications.europa.eu/resource/interinstitutionalprocedures/>t_interinstitutionalprocedure">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="basis_legal_procedure" type="{http://publications.europa.eu/resource/core-metadata}t_legal_procedure" maxOccurs="unbounded"/>
 *         &lt;element name="extension" type="{http://publications.europa.eu/resource/core-metadata}t_event_extension_base" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="work" type="{http://publications.europa.eu/resource/core-metadata}t_work"/>
 *           &lt;element name="work_ref" type="{http://publications.europa.eu/resource/core-metadata}t_work_ref"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_event_legal", namespace = "http://publications.europa.eu/resource/core-metadata", propOrder = {
    "typeEvent",
    "dateEvent",
    "agentEvent",
    "typeInterinstitutionalprocedure",
    "basisLegalProcedure",
    "extension",
    "workOrWorkRef"
})
public class TEventLegal {

    @XmlElement(name = "type_event", required = true)
    protected TEventLegal.TypeEvent typeEvent;
    @XmlElement(name = "date_event", required = true)
    protected TEventLegal.DateEvent dateEvent;
    @XmlElement(name = "agent_event", required = true)
    protected List<TAgentEvent> agentEvent;
    @XmlElement(name = "type_interinstitutionalprocedure", required = true)
    protected TEventLegal.TypeInterinstitutionalprocedure typeInterinstitutionalprocedure;
    @XmlElement(name = "basis_legal_procedure", required = true)
    protected List<TLegalProcedure> basisLegalProcedure;
    protected List<TEventExtensionBase> extension;
    @XmlElements({
        @XmlElement(name = "work", type = TWork.class),
        @XmlElement(name = "work_ref", type = TWorkRef.class)
    })
    protected List<Object> workOrWorkRef;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the typeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link TEventLegal.TypeEvent }
     *     
     */
    public TEventLegal.TypeEvent getTypeEvent() {
        return typeEvent;
    }

    /**
     * Sets the value of the typeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEventLegal.TypeEvent }
     *     
     */
    public void setTypeEvent(TEventLegal.TypeEvent value) {
        this.typeEvent = value;
    }

    /**
     * Gets the value of the dateEvent property.
     * 
     * @return
     *     possible object is
     *     {@link TEventLegal.DateEvent }
     *     
     */
    public TEventLegal.DateEvent getDateEvent() {
        return dateEvent;
    }

    /**
     * Sets the value of the dateEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEventLegal.DateEvent }
     *     
     */
    public void setDateEvent(TEventLegal.DateEvent value) {
        this.dateEvent = value;
    }

    /**
     * Gets the value of the agentEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAgentEvent }
     * 
     * 
     */
    public List<TAgentEvent> getAgentEvent() {
        if (agentEvent == null) {
            agentEvent = new ArrayList<>();
        }
        return this.agentEvent;
    }

    /**
     * Gets the value of the typeInterinstitutionalprocedure property.
     * 
     * @return
     *     possible object is
     *     {@link TEventLegal.TypeInterinstitutionalprocedure }
     *     
     */
    public TEventLegal.TypeInterinstitutionalprocedure getTypeInterinstitutionalprocedure() {
        return typeInterinstitutionalprocedure;
    }

    /**
     * Sets the value of the typeInterinstitutionalprocedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEventLegal.TypeInterinstitutionalprocedure }
     *     
     */
    public void setTypeInterinstitutionalprocedure(TEventLegal.TypeInterinstitutionalprocedure value) {
        this.typeInterinstitutionalprocedure = value;
    }

    /**
     * Gets the value of the basisLegalProcedure property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basisLegalProcedure property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasisLegalProcedure().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TLegalProcedure }
     * 
     * 
     */
    public List<TLegalProcedure> getBasisLegalProcedure() {
        if (basisLegalProcedure == null) {
            basisLegalProcedure = new ArrayList<>();
        }
        return this.basisLegalProcedure;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEventExtensionBase }
     * 
     * 
     */
    public List<TEventExtensionBase> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the workOrWorkRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the workOrWorkRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWorkOrWorkRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TWork }
     * {@link TWorkRef }
     * 
     * 
     */
    public List<Object> getWorkOrWorkRef() {
        if (workOrWorkRef == null) {
            workOrWorkRef = new ArrayList<>();
        }
        return this.workOrWorkRef;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DateEvent {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://publications.europa.eu/resource/events/>t_event">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TypeEvent {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://publications.europa.eu/resource/interinstitutionalprocedures/>t_interinstitutionalprocedure">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TypeInterinstitutionalprocedure {

        @XmlValue
        protected TInterinstitutionalprocedure value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link TInterinstitutionalprocedure }
         *     
         */
        public TInterinstitutionalprocedure getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TInterinstitutionalprocedure }
         *     
         */
        public void setValue(TInterinstitutionalprocedure value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }

}
