//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for t_expression_legis_sum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_expression_legis_sum">
 *   &lt;complexContent>
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_expression_extension_base">
 *       &lt;sequence>
 *         &lt;element name="description.summary" type="{http://publications.europa.eu/resource/core-metadata/nth}t_description_summary"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_expression_legis_sum", propOrder = {
    "descriptionSummary"
})
public class TExpressionLegisSum
    extends TExpressionExtensionBase
{

    @XmlElement(name = "description.summary", required = true)
    protected TDescriptionSummary descriptionSummary;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the descriptionSummary property.
     * 
     * @return
     *     possible object is
     *     {@link TDescriptionSummary }
     *     
     */
    public TDescriptionSummary getDescriptionSummary() {
        return descriptionSummary;
    }

    /**
     * Sets the value of the descriptionSummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link TDescriptionSummary }
     *     
     */
    public void setDescriptionSummary(TDescriptionSummary value) {
        this.descriptionSummary = value;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }

}
