//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for t_identifier_procedure complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_identifier_procedure">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;sequence>
 *           &lt;element name="year_procedure">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://publications.europa.eu/resource/core-metadata>t_year">
 *                   &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element name="number_procedure">
 *             &lt;complexType>
 *               &lt;simpleContent>
 *                 &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                   &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *                 &lt;/extension>
 *               &lt;/simpleContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/sequence>
 *         &lt;element name="procId">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_identifier_procedure", namespace = "http://publications.europa.eu/resource/core-metadata", propOrder = {
    "yearProcedure",
    "numberProcedure",
    "procId"
})
public class TIdentifierProcedure {

    @XmlElement(name = "year_procedure")
    protected TIdentifierProcedure.YearProcedure yearProcedure;
    @XmlElement(name = "number_procedure")
    protected TIdentifierProcedure.NumberProcedure numberProcedure;
    protected TIdentifierProcedure.ProcId procId;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the yearProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifierProcedure.YearProcedure }
     *     
     */
    public TIdentifierProcedure.YearProcedure getYearProcedure() {
        return yearProcedure;
    }

    /**
     * Sets the value of the yearProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifierProcedure.YearProcedure }
     *     
     */
    public void setYearProcedure(TIdentifierProcedure.YearProcedure value) {
        this.yearProcedure = value;
    }

    /**
     * Gets the value of the numberProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifierProcedure.NumberProcedure }
     *     
     */
    public TIdentifierProcedure.NumberProcedure getNumberProcedure() {
        return numberProcedure;
    }

    /**
     * Sets the value of the numberProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifierProcedure.NumberProcedure }
     *     
     */
    public void setNumberProcedure(TIdentifierProcedure.NumberProcedure value) {
        this.numberProcedure = value;
    }

    /**
     * Gets the value of the procId property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifierProcedure.ProcId }
     *     
     */
    public TIdentifierProcedure.ProcId getProcId() {
        return procId;
    }

    /**
     * Sets the value of the procId property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifierProcedure.ProcId }
     *     
     */
    public void setProcId(TIdentifierProcedure.ProcId value) {
        this.procId = value;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NumberProcedure {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ProcId {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://publications.europa.eu/resource/core-metadata>t_year">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class YearProcedure {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }

}
