//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for t_procedure_interinstitutional complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_procedure_interinstitutional">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identifier_procedure" type="{http://publications.europa.eu/resource/core-metadata}t_identifier_procedure"/>
 *         &lt;element name="extension" type="{http://publications.europa.eu/resource/core-metadata}t_procedure_extension_base" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="event_legal" type="{http://publications.europa.eu/resource/core-metadata}t_event_legal" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_procedure_interinstitutional", namespace = "http://publications.europa.eu/resource/core-metadata", propOrder = {
    "identifierProcedure",
    "extension",
    "eventLegal"
})
public class TProcedureInterinstitutional {

    @XmlElement(name = "identifier_procedure", required = true)
    protected TIdentifierProcedure identifierProcedure;
    protected List<TProcedureExtensionBase> extension;
    @XmlElement(name = "event_legal", required = true)
    protected List<TEventLegal> eventLegal;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the identifierProcedure property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifierProcedure }
     *     
     */
    public TIdentifierProcedure getIdentifierProcedure() {
        return identifierProcedure;
    }

    /**
     * Sets the value of the identifierProcedure property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifierProcedure }
     *     
     */
    public void setIdentifierProcedure(TIdentifierProcedure value) {
        this.identifierProcedure = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TProcedureExtensionBase }
     * 
     * 
     */
    public List<TProcedureExtensionBase> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the eventLegal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eventLegal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEventLegal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TEventLegal }
     * 
     * 
     */
    public List<TEventLegal> getEventLegal() {
        if (eventLegal == null) {
            eventLegal = new ArrayList<>();
        }
        return this.eventLegal;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }

}
