//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TransmissionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransmissionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="institution" type="{http://publications.europa.eu/resource/corporatebodies/}t_corporatebody"/>
 *         &lt;element name="service" type="{http://publications.europa.eu/resource/core-metadata-transmission}ServiceType"/>
 *         &lt;element name="context" type="{http://publications.europa.eu/resource/core-metadata-transmission}ContextType"/>
 *         &lt;element name="date_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="comment" type="{http://publications.europa.eu/resource/core-metadata-transmission}CommentType"/>
 *         &lt;element name="extension" type="{http://publications.europa.eu/resource/core-metadata-transmission}TransmissionExtensionBaseType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="workflow" type="{http://publications.europa.eu/resource/core-metadata-transmission}WorkflowType"/>
 *         &lt;element ref="{http://publications.europa.eu/resource/core-metadata}procedure_interinstitutional" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransmissionType", namespace = "http://publications.europa.eu/resource/core-metadata-transmission", propOrder = {
    "institution",
    "service",
    "context",
    "dateTime",
    "comment",
    "extension",
    "workflow",
    "procedureInterinstitutional"
})
public class TransmissionType {

    @XmlElement(required = true)
    protected String institution;
    @XmlElement(required = true)
    protected String service;
    @XmlElement(required = true)
    protected String context;
    @XmlElement(name = "date_time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar dateTime;
    @XmlElement(required = true)
    protected CommentType comment;
    protected List<TransmissionExtensionBaseType> extension;
    @XmlElement(required = true)
    protected WorkflowType workflow;
    @XmlElement(name = "procedure_interinstitutional", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected TProcedureInterinstitutional procedureInterinstitutional;
    @XmlAttribute(name = "id", required = true)
    protected String id;

    /**
     * Gets the value of the institution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * Sets the value of the institution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstitution(String value) {
        this.institution = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setService(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTime(XMLGregorianCalendar value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link CommentType }
     *     
     */
    public CommentType getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommentType }
     *     
     */
    public void setComment(CommentType value) {
        this.comment = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransmissionExtensionBaseType }
     * 
     * 
     */
    public List<TransmissionExtensionBaseType> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the workflow property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowType }
     *     
     */
    public WorkflowType getWorkflow() {
        return workflow;
    }

    /**
     * Sets the value of the workflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowType }
     *     
     */
    public void setWorkflow(WorkflowType value) {
        this.workflow = value;
    }

    /**
     * 
     * 						Information about the interinstitutional procedure.
     * 						Present if and only if the internal procedure enters an interinstitutional procedure.
     * 					
     * 
     * @return
     *     possible object is
     *     {@link TProcedureInterinstitutional }
     *     
     */
    public TProcedureInterinstitutional getProcedureInterinstitutional() {
        return procedureInterinstitutional;
    }

    /**
     * Sets the value of the procedureInterinstitutional property.
     * 
     * @param value
     *     allowed object is
     *     {@link TProcedureInterinstitutional }
     *     
     */
    public void setProcedureInterinstitutional(TProcedureInterinstitutional value) {
        this.procedureInterinstitutional = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
