//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_role.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_role">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ADDRESSEE"/>
 *     &lt;enumeration value="ADDRESSEE_ACT"/>
 *     &lt;enumeration value="ADDRESSEE_CONSULT"/>
 *     &lt;enumeration value="ADDRESSEE_CONSULT_MANDATORY"/>
 *     &lt;enumeration value="ADDRESSEE_CONSULT_OPTION"/>
 *     &lt;enumeration value="ADDRESSEE_INFO"/>
 *     &lt;enumeration value="ASSOC_CORP"/>
 *     &lt;enumeration value="AUT"/>
 *     &lt;enumeration value="AUTHORI"/>
 *     &lt;enumeration value="AUT_OPIN"/>
 *     &lt;enumeration value="AUT_REPORT"/>
 *     &lt;enumeration value="CHAIR"/>
 *     &lt;enumeration value="CHAIR_CMT"/>
 *     &lt;enumeration value="CHAIR_VICE"/>
 *     &lt;enumeration value="MEDIATOR"/>
 *     &lt;enumeration value="MEMBER"/>
 *     &lt;enumeration value="MEMBER_ALT"/>
 *     &lt;enumeration value="MEMBER_COM"/>
 *     &lt;enumeration value="MEMBER_EP"/>
 *     &lt;enumeration value="MEMBER_REPORT"/>
 *     &lt;enumeration value="OMBUDSMAN"/>
 *     &lt;enumeration value="PRESID"/>
 *     &lt;enumeration value="PRESID_CHAMB"/>
 *     &lt;enumeration value="PRESID_CMT"/>
 *     &lt;enumeration value="PRESID_COM"/>
 *     &lt;enumeration value="PRESID_CONSIL"/>
 *     &lt;enumeration value="PRESID_COR"/>
 *     &lt;enumeration value="PRESID_CURIA"/>
 *     &lt;enumeration value="PRESID_ECA"/>
 *     &lt;enumeration value="PRESID_EP"/>
 *     &lt;enumeration value="PRESID_EURCOU"/>
 *     &lt;enumeration value="PRESID_VICE"/>
 *     &lt;enumeration value="PRESID_VICE_COM"/>
 *     &lt;enumeration value="PRESID_VICE_FIRST"/>
 *     &lt;enumeration value="PUBLISHER"/>
 *     &lt;enumeration value="QUAESTOR"/>
 *     &lt;enumeration value="RAPP"/>
 *     &lt;enumeration value="RAPP_CO"/>
 *     &lt;enumeration value="RAPP_GEN"/>
 *     &lt;enumeration value="RAPP_OPIN"/>
 *     &lt;enumeration value="REPR_GOV"/>
 *     &lt;enumeration value="REPR_HIGH"/>
 *     &lt;enumeration value="REPR_PERM"/>
 *     &lt;enumeration value="RESP_CORP"/>
 *     &lt;enumeration value="RESP_JOINT_CORP"/>
 *     &lt;enumeration value="RESP_JOINT_PERS"/>
 *     &lt;enumeration value="RESP_PERS"/>
 *     &lt;enumeration value="SEC_GEN"/>
 *     &lt;enumeration value="SIGN"/>
 *     &lt;enumeration value="TAKING_OVER"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "t_role", namespace = "http://publications.europa.eu/resource/roles/")
@XmlEnum
public enum TRole {

    ADDRESSEE,
    ADDRESSEE_ACT,
    ADDRESSEE_CONSULT,
    ADDRESSEE_CONSULT_MANDATORY,
    ADDRESSEE_CONSULT_OPTION,
    ADDRESSEE_INFO,
    ASSOC_CORP,
    AUT,
    AUTHORI,
    AUT_OPIN,
    AUT_REPORT,
    CHAIR,
    CHAIR_CMT,
    CHAIR_VICE,
    MEDIATOR,
    MEMBER,
    MEMBER_ALT,
    MEMBER_COM,
    MEMBER_EP,
    MEMBER_REPORT,
    OMBUDSMAN,
    PRESID,
    PRESID_CHAMB,
    PRESID_CMT,
    PRESID_COM,
    PRESID_CONSIL,
    PRESID_COR,
    PRESID_CURIA,
    PRESID_ECA,
    PRESID_EP,
    PRESID_EURCOU,
    PRESID_VICE,
    PRESID_VICE_COM,
    PRESID_VICE_FIRST,
    PUBLISHER,
    QUAESTOR,
    RAPP,
    RAPP_CO,
    RAPP_GEN,
    RAPP_OPIN,
    REPR_GOV,
    REPR_HIGH,
    REPR_PERM,
    RESP_CORP,
    RESP_JOINT_CORP,
    RESP_JOINT_PERS,
    RESP_PERS,
    SEC_GEN,
    SIGN,
    TAKING_OVER;

    public String value() {
        return name();
    }

    public static TRole fromValue(String v) {
        return valueOf(v);
    }

}
