//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for t_treaty.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="t_treaty">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACC_1972"/>
 *     &lt;enumeration value="ACC_1973"/>
 *     &lt;enumeration value="ACC_1979"/>
 *     &lt;enumeration value="ACC_1985"/>
 *     &lt;enumeration value="ACC_1994"/>
 *     &lt;enumeration value="ACC_1995"/>
 *     &lt;enumeration value="ACC_2003"/>
 *     &lt;enumeration value="ACC_2005"/>
 *     &lt;enumeration value="ACC_2012"/>
 *     &lt;enumeration value="AMS"/>
 *     &lt;enumeration value="BUDG_1970"/>
 *     &lt;enumeration value="CECA_1951"/>
 *     &lt;enumeration value="CHAR_2007"/>
 *     &lt;enumeration value="CHAR_2010"/>
 *     &lt;enumeration value="EEA"/>
 *     &lt;enumeration value="EURATOM_1957"/>
 *     &lt;enumeration value="EURATOM_2010"/>
 *     &lt;enumeration value="FINAN_1975"/>
 *     &lt;enumeration value="FUSION"/>
 *     &lt;enumeration value="LIS"/>
 *     &lt;enumeration value="LIS_CORR"/>
 *     &lt;enumeration value="NICE"/>
 *     &lt;enumeration value="PRO_ANT"/>
 *     &lt;enumeration value="SCHENGEN"/>
 *     &lt;enumeration value="SEA"/>
 *     &lt;enumeration value="TCONS_2004"/>
 *     &lt;enumeration value="TEC_1992"/>
 *     &lt;enumeration value="TEC_1997"/>
 *     &lt;enumeration value="TEC_2002"/>
 *     &lt;enumeration value="TEC_2006"/>
 *     &lt;enumeration value="TEEC_1957"/>
 *     &lt;enumeration value="TEU_1992"/>
 *     &lt;enumeration value="TEU_1997"/>
 *     &lt;enumeration value="TEU_2002"/>
 *     &lt;enumeration value="TEU_2006"/>
 *     &lt;enumeration value="TEU_2008"/>
 *     &lt;enumeration value="TEU_2010"/>
 *     &lt;enumeration value="TFEU_2008"/>
 *     &lt;enumeration value="TFEU_2010"/>
 *     &lt;enumeration value="TGREENL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "t_treaty", namespace = "http://publications.europa.eu/resource/treaties/")
@XmlEnum
public enum TTreaty {

    ACC_1972,
    ACC_1973,
    ACC_1979,
    ACC_1985,
    ACC_1994,
    ACC_1995,
    ACC_2003,
    ACC_2005,
    ACC_2012,
    AMS,
    BUDG_1970,
    CECA_1951,
    CHAR_2007,
    CHAR_2010,
    EEA,
    EURATOM_1957,
    EURATOM_2010,
    FINAN_1975,
    FUSION,
    LIS,
    LIS_CORR,
    NICE,
    PRO_ANT,
    SCHENGEN,
    SEA,
    TCONS_2004,
    TEC_1992,
    TEC_1997,
    TEC_2002,
    TEC_2006,
    TEEC_1957,
    TEU_1992,
    TEU_1997,
    TEU_2002,
    TEU_2006,
    TEU_2008,
    TEU_2010,
    TFEU_2008,
    TFEU_2010,
    TGREENL;

    public String value() {
        return name();
    }

    public static TTreaty fromValue(String v) {
        return valueOf(v);
    }

}
