//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for t_work complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_work">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type_work">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://publications.europa.eu/resource/resourcetypes/>t_resource-type">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="identifier_work">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="agent_work" type="{http://publications.europa.eu/resource/core-metadata}t_agent_work" maxOccurs="unbounded"/>
 *         &lt;element name="date_work">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="version_work" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://publications.europa.eu/resource/core-metadata>t_legalresourceversion">
 *                 &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="extension" type="{http://publications.europa.eu/resource/core-metadata}t_work_extension_base" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="expression" type="{http://publications.europa.eu/resource/core-metadata}t_expression" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_work", namespace = "http://publications.europa.eu/resource/core-metadata", propOrder = {
    "typeWork",
    "identifierWork",
    "agentWork",
    "dateWork",
    "versionWork",
    "extension",
    "expression"
})
public class TWork {

    @XmlElement(name = "type_work", required = true)
    protected TWork.TypeWork typeWork;
    @XmlElement(name = "identifier_work", required = true)
    protected TWork.IdentifierWork identifierWork;
    @XmlElement(name = "agent_work", required = true)
    protected List<TAgentWork> agentWork;
    @XmlElement(name = "date_work", required = true)
    protected TWork.DateWork dateWork;
    @XmlElement(name = "version_work")
    protected TWork.VersionWork versionWork;
    protected List<TWorkExtensionBase> extension;
    protected List<TExpression> expression;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the typeWork property.
     * 
     * @return
     *     possible object is
     *     {@link TWork.TypeWork }
     *     
     */
    public TWork.TypeWork getTypeWork() {
        return typeWork;
    }

    /**
     * Sets the value of the typeWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWork.TypeWork }
     *     
     */
    public void setTypeWork(TWork.TypeWork value) {
        this.typeWork = value;
    }

    /**
     * Gets the value of the identifierWork property.
     * 
     * @return
     *     possible object is
     *     {@link TWork.IdentifierWork }
     *     
     */
    public TWork.IdentifierWork getIdentifierWork() {
        return identifierWork;
    }

    /**
     * Sets the value of the identifierWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWork.IdentifierWork }
     *     
     */
    public void setIdentifierWork(TWork.IdentifierWork value) {
        this.identifierWork = value;
    }

    /**
     * Gets the value of the agentWork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agentWork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgentWork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TAgentWork }
     * 
     * 
     */
    public List<TAgentWork> getAgentWork() {
        if (agentWork == null) {
            agentWork = new ArrayList<>();
        }
        return this.agentWork;
    }

    /**
     * Gets the value of the dateWork property.
     * 
     * @return
     *     possible object is
     *     {@link TWork.DateWork }
     *     
     */
    public TWork.DateWork getDateWork() {
        return dateWork;
    }

    /**
     * Sets the value of the dateWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWork.DateWork }
     *     
     */
    public void setDateWork(TWork.DateWork value) {
        this.dateWork = value;
    }

    /**
     * Gets the value of the versionWork property.
     * 
     * @return
     *     possible object is
     *     {@link TWork.VersionWork }
     *     
     */
    public TWork.VersionWork getVersionWork() {
        return versionWork;
    }

    /**
     * Sets the value of the versionWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link TWork.VersionWork }
     *     
     */
    public void setVersionWork(TWork.VersionWork value) {
        this.versionWork = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TWorkExtensionBase }
     * 
     * 
     */
    public List<TWorkExtensionBase> getExtension() {
        if (extension == null) {
            extension = new ArrayList<>();
        }
        return this.extension;
    }

    /**
     * Gets the value of the expression property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expression property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpression().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TExpression }
     * 
     * 
     */
    public List<TExpression> getExpression() {
        if (expression == null) {
            expression = new ArrayList<>();
        }
        return this.expression;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>date">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DateWork {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class IdentifierWork {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://publications.europa.eu/resource/resourcetypes/>t_resource-type">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class TypeWork {

        @XmlValue
        protected TResourceType value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link TResourceType }
         *     
         */
        public TResourceType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link TResourceType }
         *     
         */
        public void setValue(TResourceType value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://publications.europa.eu/resource/core-metadata>t_legalresourceversion">
     *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class VersionWork {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
        protected Boolean _public;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the public property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isPublic() {
            if (_public == null) {
                return true;
            } else {
                return _public;
            }
        }

        /**
         * Sets the value of the public property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setPublic(Boolean value) {
            this._public = value;
        }

    }

}
