//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for t_work_cc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_work_cc">
 *   &lt;complexContent>
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_work_extension_base">
 *       &lt;sequence>
 *         &lt;element name="place_adoption" type="{http://publications.europa.eu/resource/core-metadata/nth}t_place_adoption"/>
 *         &lt;element name="language_authentic" type="{http://publications.europa.eu/resource/core-metadata}t_languages"/>
 *         &lt;element name="identifier_egreffe" type="{http://publications.europa.eu/resource/core-metadata/nth}t_identifier_egreffe"/>
 *         &lt;element name="relevance_EEA" type="{http://publications.europa.eu/resource/core-metadata/nth}t_yesno"/>
 *         &lt;element name="language_expected" type="{http://publications.europa.eu/resource/core-metadata}t_languages"/>
 *         &lt;element name="language_original" type="{http://publications.europa.eu/resource/core-metadata}t_languages"/>
 *         &lt;element name="number_procedure_internal" type="{http://publications.europa.eu/resource/core-metadata/nth}t_number_procedure_internal" minOccurs="0"/>
 *         &lt;element name="date_transmission_addressee" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="identifier_COM_document_related" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="identifier_SWD_document_related" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="corrigendum" type="{http://publications.europa.eu/resource/core-metadata/nth}t_yesno"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_work_cc", propOrder = {
    "placeAdoption",
    "languageAuthentic",
    "identifierEgreffe",
    "relevanceEEA",
    "languageExpected",
    "languageOriginal",
    "numberProcedureInternal",
    "dateTransmissionAddressee",
    "identifierCOMDocumentRelated",
    "identifierSWDDocumentRelated",
    "corrigendum"
})
public class TWorkCc
    extends TWorkExtensionBase
{

    @XmlElement(name = "place_adoption", required = true)
    protected TPlaceAdoption placeAdoption;
    @XmlList
    @XmlElement(name = "language_authentic", required = true)
    protected List<String> languageAuthentic;
    @XmlElement(name = "identifier_egreffe", required = true)
    protected TIdentifierEgreffe identifierEgreffe;
    @XmlElement(name = "relevance_EEA", required = true)
    protected TYesno relevanceEEA;
    @XmlList
    @XmlElement(name = "language_expected", required = true)
    protected List<String> languageExpected;
    @XmlList
    @XmlElement(name = "language_original", required = true)
    protected List<String> languageOriginal;
    @XmlElement(name = "number_procedure_internal")
    protected TNumberProcedureInternal numberProcedureInternal;
    @XmlElement(name = "date_transmission_addressee", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateTransmissionAddressee;
    @XmlElement(name = "identifier_COM_document_related")
    protected List<String> identifierCOMDocumentRelated;
    @XmlElement(name = "identifier_SWD_document_related")
    protected List<String> identifierSWDDocumentRelated;
    @XmlElement(required = true)
    protected TYesno corrigendum;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the placeAdoption property.
     * 
     * @return
     *     possible object is
     *     {@link TPlaceAdoption }
     *     
     */
    public TPlaceAdoption getPlaceAdoption() {
        return placeAdoption;
    }

    /**
     * Sets the value of the placeAdoption property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPlaceAdoption }
     *     
     */
    public void setPlaceAdoption(TPlaceAdoption value) {
        this.placeAdoption = value;
    }

    /**
     * Gets the value of the languageAuthentic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageAuthentic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageAuthentic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguageAuthentic() {
        if (languageAuthentic == null) {
            languageAuthentic = new ArrayList<>();
        }
        return this.languageAuthentic;
    }

    /**
     * Gets the value of the identifierEgreffe property.
     * 
     * @return
     *     possible object is
     *     {@link TIdentifierEgreffe }
     *     
     */
    public TIdentifierEgreffe getIdentifierEgreffe() {
        return identifierEgreffe;
    }

    /**
     * Sets the value of the identifierEgreffe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TIdentifierEgreffe }
     *     
     */
    public void setIdentifierEgreffe(TIdentifierEgreffe value) {
        this.identifierEgreffe = value;
    }

    /**
     * Gets the value of the relevanceEEA property.
     * 
     * @return
     *     possible object is
     *     {@link TYesno }
     *     
     */
    public TYesno getRelevanceEEA() {
        return relevanceEEA;
    }

    /**
     * Sets the value of the relevanceEEA property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYesno }
     *     
     */
    public void setRelevanceEEA(TYesno value) {
        this.relevanceEEA = value;
    }

    /**
     * Gets the value of the languageExpected property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageExpected property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageExpected().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguageExpected() {
        if (languageExpected == null) {
            languageExpected = new ArrayList<>();
        }
        return this.languageExpected;
    }

    /**
     * Gets the value of the languageOriginal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the languageOriginal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguageOriginal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguageOriginal() {
        if (languageOriginal == null) {
            languageOriginal = new ArrayList<>();
        }
        return this.languageOriginal;
    }

    /**
     * Gets the value of the numberProcedureInternal property.
     * 
     * @return
     *     possible object is
     *     {@link TNumberProcedureInternal }
     *     
     */
    public TNumberProcedureInternal getNumberProcedureInternal() {
        return numberProcedureInternal;
    }

    /**
     * Sets the value of the numberProcedureInternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNumberProcedureInternal }
     *     
     */
    public void setNumberProcedureInternal(TNumberProcedureInternal value) {
        this.numberProcedureInternal = value;
    }

    /**
     * Gets the value of the dateTransmissionAddressee property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateTransmissionAddressee() {
        return dateTransmissionAddressee;
    }

    /**
     * Sets the value of the dateTransmissionAddressee property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateTransmissionAddressee(XMLGregorianCalendar value) {
        this.dateTransmissionAddressee = value;
    }

    /**
     * Gets the value of the identifierCOMDocumentRelated property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifierCOMDocumentRelated property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifierCOMDocumentRelated().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIdentifierCOMDocumentRelated() {
        if (identifierCOMDocumentRelated == null) {
            identifierCOMDocumentRelated = new ArrayList<>();
        }
        return this.identifierCOMDocumentRelated;
    }

    /**
     * Gets the value of the identifierSWDDocumentRelated property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the identifierSWDDocumentRelated property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdentifierSWDDocumentRelated().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getIdentifierSWDDocumentRelated() {
        if (identifierSWDDocumentRelated == null) {
            identifierSWDDocumentRelated = new ArrayList<>();
        }
        return this.identifierSWDDocumentRelated;
    }

    /**
     * Gets the value of the corrigendum property.
     * 
     * @return
     *     possible object is
     *     {@link TYesno }
     *     
     */
    public TYesno getCorrigendum() {
        return corrigendum;
    }

    /**
     * Sets the value of the corrigendum property.
     * 
     * @param value
     *     allowed object is
     *     {@link TYesno }
     *     
     */
    public void setCorrigendum(TYesno value) {
        this.corrigendum = value;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }

}
