//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.26 at 09:07:40 AM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.view.business.egreffe.metadata;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for t_work_layer0 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="t_work_layer0">
 *   &lt;complexContent>
 *     &lt;extension base="{http://publications.europa.eu/resource/core-metadata}t_work_extension_base">
 *       &lt;sequence>
 *         &lt;element name="part_of_work" type="{http://publications.europa.eu/resource/core-metadata/nth}t_part_of_work" minOccurs="0"/>
 *         &lt;element name="sequence_part" type="{http://publications.europa.eu/resource/core-metadata/nth}t_sequence_part" minOccurs="0"/>
 *         &lt;element name="contains_work" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="number_parts" type="{http://publications.europa.eu/resource/core-metadata/nth}t_number_parts"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://publications.europa.eu/resource/core-metadata}public"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "t_work_layer0", propOrder = {
    "partOfWork",
    "sequencePart",
    "containsWork",
    "numberParts"
})
public class TWorkLayer0
    extends TWorkExtensionBase
{

    @XmlElement(name = "part_of_work")
    protected TPartOfWork partOfWork;
    @XmlElement(name = "sequence_part")
    protected TSequencePart sequencePart;
    @XmlElement(name = "contains_work")
    protected List<String> containsWork;
    @XmlElement(name = "number_parts", required = true)
    protected TNumberParts numberParts;
    @XmlAttribute(name = "public", namespace = "http://publications.europa.eu/resource/core-metadata")
    protected Boolean _public;

    /**
     * Gets the value of the partOfWork property.
     * 
     * @return
     *     possible object is
     *     {@link TPartOfWork }
     *     
     */
    public TPartOfWork getPartOfWork() {
        return partOfWork;
    }

    /**
     * Sets the value of the partOfWork property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPartOfWork }
     *     
     */
    public void setPartOfWork(TPartOfWork value) {
        this.partOfWork = value;
    }

    /**
     * Gets the value of the sequencePart property.
     * 
     * @return
     *     possible object is
     *     {@link TSequencePart }
     *     
     */
    public TSequencePart getSequencePart() {
        return sequencePart;
    }

    /**
     * Sets the value of the sequencePart property.
     * 
     * @param value
     *     allowed object is
     *     {@link TSequencePart }
     *     
     */
    public void setSequencePart(TSequencePart value) {
        this.sequencePart = value;
    }

    /**
     * Gets the value of the containsWork property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containsWork property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainsWork().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getContainsWork() {
        if (containsWork == null) {
            containsWork = new ArrayList<>();
        }
        return this.containsWork;
    }

    /**
     * Gets the value of the numberParts property.
     * 
     * @return
     *     possible object is
     *     {@link TNumberParts }
     *     
     */
    public TNumberParts getNumberParts() {
        return numberParts;
    }

    /**
     * Sets the value of the numberParts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TNumberParts }
     *     
     */
    public void setNumberParts(TNumberParts value) {
        this.numberParts = value;
    }

    /**
     * Gets the value of the public property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPublic() {
        if (_public == null) {
            return true;
        } else {
            return _public;
        }
    }

    /**
     * Sets the value of the public property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPublic(Boolean value) {
        this._public = value;
    }

}
