-- Create table

CREATE TABLE `ETX_WEB_PARTY_ICA`
(
  `PCA_ID`              DECIMAL(19,0) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `PAR_ID`              DECIMAL(19,0) NOT NULL,
  `PCA_NODE_NAME`       VARCHAR(64) NOT NULL,
  `PCA_DISPLAY_NAME`    VARCHAR(75) NOT NULL,
  `PCA_LOADED_ON`       DATETIME NOT NULL,
  `PCA_INTEGRITY`       TINYINT,
  `PCA_CONFIDENTIALITY` TINYINT,
  `PCA_CERTIFICATE`     LONGTEXT,
  `PCA_CREATED_ON`      DATETIME DEFAULT SYSDATE() NOT NULL,
  `PCA_CREATED_BY`      DECIMAL(19,0) NOT NULL,
  `PCA_UPDATED_ON`      DATETIME,
  `PCA_UPDATED_BY`      DECIMAL(19,0),
  `PCA_STATE`           TINYINT NOT NULL,
CONSTRAINT FK_PCA_PAR_ID FOREIGN KEY (PAR_ID) REFERENCES ETX_WEB_PARTY(PAR_ID),
CONSTRAINT FK_PCA_CREATED_USR_ID FOREIGN KEY (PCA_CREATED_BY) REFERENCES ETX_WEB_USER(USR_ID),
CONSTRAINT FK_PCA_UPDATED_USR_ID FOREIGN KEY (PCA_UPDATED_BY) REFERENCES ETX_WEB_USER(USR_ID)
);

-- Data migration

INSERT
INTO ETX_WEB_PARTY_ICA (PCA_ID, PAR_ID, PCA_NODE_NAME, PCA_DISPLAY_NAME, PCA_CREATED_BY, PCA_LOADED_ON, PCA_INTEGRITY, PCA_CONFIDENTIALITY,
    PCA_CERTIFICATE, PCA_CREATED_ON, PCA_UPDATED_ON, PCA_UPDATED_BY, PCA_STATE)
      SELECT ETX_WEB_PARTYICASEQ.nextval, p.PAR_ID, bc.BCG_PROPERTY_VALUE, bc.BCG_PROPERTY_VALUE, 0, SYSDATE(), null, null, null, SYSDATE(), null, null, 1
        FROM ETX_WEB_PARTY p JOIN ETX_WEB_BUSINESS_CONFIG bc
        ON p.BUS_ID = bc.BUS_ID
        WHERE bc.BCG_PROPERTY_NAME = 'etx.business.receiver.node.party.name';

-- Remove config property

DELETE FROM ETX_WEB_BUSINESS_CONFIG WHERE BCG_PROPERTY_NAME = 'etx.business.receiver.node.party.name';

-- Label translation

INSERT INTO ETX_WEB_LABEL_TRANSLATION(LTR_KEY, LTR_MESSAGE, LTR_SCREEN_ID, LTR_SCREEN_POSITION_X, LTR_SCREEN_POSITION_Y, LNG_ID)
VALUES ('message.recipientErrorMessage', 'Please enter a Recipient', 1, 1, 1, 1);