swagger: '2.0'
info:
  description: >-
    This document describes the API of the RESTful services to be consumed by
    the e-TrustEx Mobile application.
  version: '0.1'
  title: e-TrustEx Mobile Application
host: webgate.acceptance.ec.europa.eu
basePath: /e-trustex/mobile/services
tags:
  - name: user
    description: Retrieve information about the logged user
  - name: parties
    description: Retrieve party and message information
schemes:
  - http
paths:
  /user:
    get:
      tags:
        - user
      summary: Get logged user information
      description: ''
      operationId: getUserByName
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/User'
        '500':
          description: internal server error
  /parties:
    get:
      tags:
        - parties
      summary: Get parties for logged user
      description: ''
      operationId: getPartiesByUsername
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Parties'
        '500':
          description: internal server error
  '/parties/{partyId}/inboxcounters':
    get:
      tags:
        - parties
      summary: Get count of all and read messages in inbox
      description: ''
      operationId: getInboxCountersByParty
      produces:
        - application/xml
        - application/json
      parameters:
        - name: partyId
          in: path
          description: ID of party
          required: true
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/InboxCounters'
        '400':
          description: Invalid ID supplied
        '404':
          description: Party not found
        '500':
          description: internal server error
  '/parties/{partyId}/inbox':
    get:
      tags:
        - parties
      summary: Get inbox messages
      description: ''
      operationId: getInboxMessages
      produces:
        - application/xml
        - application/json
      parameters:
        - name: partyId
          in: path
          description: ID of party
          required: true
          type: string
        - name: startfrom
          in: query
          description: the index of the messages in the full list
          required: true
          type: string
        - name: resultsize
          in: query
          description: the number of messages fetched from the server
          required: true
          type: string
        - name: filter
          in: query
          description: filter option
          type: string
        - name: sortby
          in: query
          description: sorting option
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Inbox'
        '400':
          description: Invalid ID supplied
        '404':
          description: Party not found
        '500':
          description: internal server error
definitions:
  User:
    type: object
    properties:
      username:
        type: string
      name:
        type: string
    xml:
      name: User
  Parties:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Party'
    xml:
      name: Parties
  Party:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
    xml:
      name: Party
  Inbox:
    type: object
    properties:
      messages:
        type: array
        items:
          $ref: '#/definitions/Message'
      messageCount:
        type: string
      hasMoreMessages:
        type: boolean
    xml:
      name: Inbox
  Message:
    type: object
    properties:
      id:
        type: string
      sender:
        type: string
      recipient:
        type: string
      receiptDate:
        type: string
        format: date-time
      subject:
        type: string
      content:
        type: string
      attachmentCount:
        type: string
      totalAttachmentSize:
        type: string
      expirationDate:
        type: string
        format: date-time
      status:
        type: string
      expired:
        type: string
      contentEncrypted:
        type: string
    xml:
      name: Message
  InboxCounters:
    type: object
    properties:
      all:
        type: string
      read:
        type: string
    xml:
      name: InboxCounters
