ALTER TABLE ETX_WEB_PARTY ADD PAR_CONSUME_NODE_MSG NUMBER(1,0)
/

UPDATE ETX_WEB_PARTY SET PAR_CONSUME_NODE_MSG = 1
/

ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_CONSUME_NODE_MSG DEFAULT 1 NOT NULL ENABLE)
/

ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_DISPLAY_NAME VARCHAR2(75 CHAR))
/