DROP DATABASE IF EXISTS `etrustex`;
CREATE DATABASE `etrustex`;
USE etrustex;
SET GLOBAL FOREIGN_KEY_CHECKS=1;
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE TABLE `CPA_TB_BUSINESS_DOMAIN` (
  `CBD_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `CBD_NAME` varchar(255) NOT NULL,
  `CBD_RESP_SIG_REQUIRED` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`CBD_ID`),
  UNIQUE KEY `CBD_NAME` (`CBD_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CPA_TB_EVT_NOTIF` (
	`EVT_ID` bigint(20) NOT NULL AUTO_INCREMENT, 
	`CRE_DT` datetime, 
	`CRE_ID` varchar(255), 
	`MOD_DT` datetime, 
	`MOD_ID` varchar(255), 
	`EVT_PRO_ID` bigint(20) NOT NULL, 
	`EVT_CBD_ID` bigint(20) NOT NULL, 
	`EVT_PTY_ID` bigint(20) NOT NULL, 
	`EVT_TYPE` varchar(255),
	PRIMARY KEY (`EVT_ID`),
	KEY `EVT_UK_IDX` (`EVT_PRO_ID`, `EVT_CBD_ID`, `EVT_PTY_ID`, `EVT_TYPE`),
	UNIQUE KEY `EVT_UK_ID` (`EVT_PRO_ID`, `EVT_CBD_ID`, `EVT_PTY_ID`, `EVT_TYPE`),
	CONSTRAINT `CNN_FK_CBD_ID` FOREIGN KEY (`EVT_CBD_ID`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`),
	CONSTRAINT `CNN_FK_PRO_ID` FOREIGN KEY (`EVT_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`),
	CONSTRAINT `CNN_FK_PTY_ID` FOREIGN KEY (`EVT_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CPA_TB_USER` (
  `CUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `CUS_NAME` varchar(255) NOT NULL,
  `CUS_PASSW` varchar(255) NOT NULL,
  PRIMARY KEY (`CUS_ID`),
  KEY `CUS_UK_IDX` (`CUS_NAME`),
  UNIQUE KEY `CUS_UK` (`CUS_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CPA_TB_USER_ROLE` (
  `RDL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `RDL_CODE` varchar(255) NOT NULL,
  `RDL_DESC` varchar(255) NOT NULL,
  PRIMARY KEY (`RDL_ID`),
  UNIQUE KEY `RDL_CODE` (`RDL_CODE`),
  UNIQUE KEY `RDL_DESC` (`RDL_DESC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_CREDENTIALS` (
  `CRED_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `CRED_CERT` varchar(255) DEFAULT NULL,
  `CRED_PASSW` varchar(255) NOT NULL,
  `CRED_PASSW_ENCRYPTED` tinyint(1) NOT NULL,
  `CRED_SIG_REQUIRED` tinyint(1) NOT NULL,
  `CRED_USER` varchar(255) NOT NULL,
  `CRED_TYPE` varchar(255) DEFAULT NULL,
  `CRED_SALTED` tinyint(1) DEFAULT 0,
  `IV` TINYBLOB,
  PRIMARY KEY (`CRED_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_CERTIFICATE` (
  `CERT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `CERT_ATTRIBUTES` varchar(255) DEFAULT NULL,
  `CERT_ENCODED_DATA` longtext DEFAULT NULL,
  `CERT_HOLDER` varchar(400) NOT NULL,
  `CERT_ISSUER` varchar(400) NOT NULL,
  `CERT_SERIAL_NR` varchar(255) NOT NULL,
  `CERT_SIGN_ALG` varchar(255) DEFAULT NULL,
  `CERT_SIGN_VAL` varchar(255) DEFAULT NULL,
  `CERT_TYPE` varchar(255) NOT NULL,
  `CERT_USAGE` varchar(255) NOT NULL,
  `CERT_VALID_TO` datetime DEFAULT NULL,
  `CERT_VALID_FROM` datetime DEFAULT NULL,
  `CERT_VERSION` varchar(255) DEFAULT NULL,
  `CERT_ACTIVE_FLAG` tinyint(1) DEFAULT 1,
  `CERT_PTY_ID` bigint(20) DEFAULT NULL,
  `CERT_REVOKED_FLAG` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`CERT_ID`),
  KEY `ETR_FK_CERTIFICATE_PARTY` (`CERT_PTY_ID`),
  CONSTRAINT `ETR_FK_CERTIFICATE_PARTY` FOREIGN KEY (`CERT_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_CIA_LEVEL` (
  `CIA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `CIA_AVAILABILITY_LVL` int(11) NOT NULL,
  `CIA_CONFIDENTIALITY_LVL` int(11) NOT NULL,
  `CIA_INTEGRITY_LVL` int(11) NOT NULL,
  PRIMARY KEY (`CIA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PARTY` (
  `PTY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `PTY_PARTY_NAME` varchar(255) NOT NULL,
  `PTY_THIRD_PTY_FL` tinyint(1) DEFAULT NULL,
  `PTY_BUSINESS_DOMAIN` bigint(20) DEFAULT NULL,
  `PTY_CRED_ID` bigint(20) DEFAULT NULL,
  `PTY_NATURAL_PERS_FL` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`PTY_ID`),
  UNIQUE KEY `PTY_PARTY_NAME_2` (`PTY_PARTY_NAME`,`PTY_BUSINESS_DOMAIN`),
  KEY `FK92B82CF1E5C12197` (`PTY_BUSINESS_DOMAIN`),
  KEY `FK92B82CF16BEB6763` (`PTY_CRED_ID`),
  CONSTRAINT `FK92B82CF16BEB6763` FOREIGN KEY (`PTY_CRED_ID`) REFERENCES `ETR_TB_CREDENTIALS` (`CRED_ID`),
  CONSTRAINT `FK92B82CF1E5C12197` FOREIGN KEY (`PTY_BUSINESS_DOMAIN`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `CPA_TB_USER_RIGHTS` (
  `CUR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `CUR_BUD_ID` bigint(20) DEFAULT NULL,
  `CUR_PTY_ID` bigint(20) DEFAULT NULL,
  `CUR_URR_ID` bigint(20) DEFAULT NULL,
  `CUR_USR_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`CUR_ID`),
  KEY `CPA_UK_USER_RIGHTS_IDX` (`CUR_BUD_ID`, `CUR_PTY_ID`, `CUR_URR_ID`, `CUR_USR_ID`),
  UNIQUE KEY `CPA_UK_USER_RIGHTS` (`CUR_BUD_ID`, `CUR_PTY_ID`, `CUR_URR_ID`, `CUR_USR_ID`),
  CONSTRAINT `FKCD084AA58161C2EA` FOREIGN KEY (`CUR_USR_ID`) REFERENCES `CPA_TB_USER` (`CUS_ID`),
  CONSTRAINT `FKCD084AA51589B62F` FOREIGN KEY (`CUR_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FKCD084AA5ABEBE57F` FOREIGN KEY (`CUR_URR_ID`) REFERENCES `CPA_TB_USER_ROLE` (`RDL_ID`),
  CONSTRAINT `FKCD084AA5F152CD46` FOREIGN KEY (`CUR_BUD_ID`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_STATE_MACHINE` (
  `SM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SM_DEFINITION` longtext,
  PRIMARY KEY (`SM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_DOCUMENT` (
  `DOC_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `DOC_TYPE_CD` varchar(255) DEFAULT NULL,
  `DOC_LOCAL_NAME` varchar(255) NOT NULL,
  `DOC_NAME` varchar(255) NOT NULL,
  `DOC_NAMESPACE` varchar(255) DEFAULT NULL,
  `DOC_VERSION` varchar(255) DEFAULT NULL,
  `DOC_SM_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DOC_ID`),
  KEY `FKD3300310152F5AC0` (`DOC_SM_ID`),
  CONSTRAINT `FKD3300310152F5AC0` FOREIGN KEY (`DOC_SM_ID`) REFERENCES `ETR_TB_STATE_MACHINE` (`SM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PROFILE` (
  `PRO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `PRO_NAME` varchar(255) NOT NULL,
  `PRO_NAMESPACE` varchar(255) DEFAULT NULL,
  `PRO_CIA_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PRO_ID`),
  KEY `FKE23240F4C58BE095` (`PRO_CIA_ID`),
  CONSTRAINT `FKE23240F4C58BE095` FOREIGN KEY (`PRO_CIA_ID`) REFERENCES `ETR_TB_CIA_LEVEL` (`CIA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PROFILE_BUSINESS_DOMAIN` (
  `PBD_PRO_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PBD_BD_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PBD_PRO_ID`, `PBD_BD_ID`),
  KEY `ETR_FK_PROFILE_BDO_BDO` (`PBD_BD_ID`),
  KEY `ETR_FK_PROFILE_BDO_PROFILE` (`PBD_PRO_ID`),
  CONSTRAINT `ETR_FK_PROFILE_BDO_BDO` FOREIGN KEY (`PBD_BD_ID`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`),
  CONSTRAINT `ETR_FK_PROFILE_BDO_PROFILE` FOREIGN KEY (`PBD_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_INTERCHANGE_AGR` (
  `ICA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `ICA_VAL_START_DT` datetime DEFAULT NULL,
  `INT_CIA_ID` bigint(20) DEFAULT NULL,
  `ICA_PRO_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ICA_ID`),
  KEY `FKFF481E04CDDDED13` (`INT_CIA_ID`),
  KEY `FKFF481E042FA8EAD3` (`ICA_PRO_ID`),
  CONSTRAINT `FKFF481E042FA8EAD3` FOREIGN KEY (`ICA_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`),
  CONSTRAINT `FKFF481E04CDDDED13` FOREIGN KEY (`INT_CIA_ID`) REFERENCES `ETR_TB_CIA_LEVEL` (`CIA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_ROLE` (
  `ROL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `ROL_IS_BIDIRECTIONAL` tinyint(1) DEFAULT NULL,
  `ROL_CODE` varchar(255) NOT NULL,
  `ROL_NAME` varchar(255) NOT NULL,
  `ROL_IS_TECHNICAL` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ROL_ID`),
  UNIQUE KEY `ROL_CODE` (`ROL_CODE`),
  UNIQUE KEY `ROL_NAME` (`ROL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_SEMAPHORE` (
  `SEM_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `SEM_NAME` varchar(255) DEFAULT NULL,
  `SEM_LAST_UPDATE` datetime DEFAULT NULL,
  `SEM_LOCKED` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`SEM_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ETR_TB_TRANSACTION` (
  `TRA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `TRA_NAME` varchar(255) NOT NULL,
  `TRA_NAMESPACE` varchar(255) DEFAULT NULL,
  `TRA_REQ_LOCAL_NAME` varchar(255) DEFAULT NULL,
  `TRA_RES_LOCAL_NAME` varchar(255) DEFAULT NULL,
  `TRA_VERSION` varchar(255) DEFAULT NULL,
  `TRA_CIA_ID` bigint(20) DEFAULT NULL,
  `TRA_DOC_ID` bigint(20) DEFAULT NULL,
  `TRA_REC_ROL_ID` bigint(20) DEFAULT NULL,
  `TRA_SEN_ROL_ID` bigint(20) DEFAULT NULL,
  `TRA_TYPE_CD` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`TRA_ID`),
  KEY `FK81A2E4A9E86130DF` (`TRA_CIA_ID`),
  KEY `FK81A2E4A968C364D4` (`TRA_DOC_ID`),
  KEY `FK81A2E4A94F545E47` (`TRA_REC_ROL_ID`),
  KEY `FK81A2E4A9BA4ABCFB` (`TRA_SEN_ROL_ID`),
  CONSTRAINT `FK81A2E4A9BA4ABCFB` FOREIGN KEY (`TRA_SEN_ROL_ID`) REFERENCES `ETR_TB_ROLE` (`ROL_ID`),
  CONSTRAINT `FK81A2E4A94F545E47` FOREIGN KEY (`TRA_REC_ROL_ID`) REFERENCES `ETR_TB_ROLE` (`ROL_ID`),
  CONSTRAINT `FK81A2E4A968C364D4` FOREIGN KEY (`TRA_DOC_ID`) REFERENCES `ETR_TB_DOCUMENT` (`DOC_ID`),
  CONSTRAINT `FK81A2E4A9E86130DF` FOREIGN KEY (`TRA_CIA_ID`) REFERENCES `ETR_TB_CIA_LEVEL` (`CIA_ID`),
  UNIQUE KEY `ETR_UK_TRANSACTION_NAME` (`TRA_NAME`, `TRA_VERSION`),
  UNIQUE KEY `ETR_UK_TRANSACTION_NAMESPACE` (`TRA_NAMESPACE`, `TRA_REQ_LOCAL_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_ENDPOINT` (
  `EDP_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EDP_ACTIVE_FLAG` tinyint(1) NOT NULL,
  `EDP_PROXY_HOST` varchar(255) DEFAULT NULL,
  `EDP_PROXY_PORT` int(11) DEFAULT NULL,
  `EDP_USE_PROXY` tinyint(1) DEFAULT NULL,
  `EDP_CRED_ID` bigint(20) DEFAULT NULL,
  `EDP_ICA_ID` bigint(20) DEFAULT NULL,
  `EDP_PTY_ID` bigint(20) DEFAULT NULL,
  `EDP_PRO_ID` bigint(20) DEFAULT NULL,
  `EDP_PROXY_CRED_ID` bigint(20) DEFAULT NULL,
  `EDP_TRA_ID` bigint(20) DEFAULT NULL,
  `EDP_BD_ID` bigint(20) DEFAULT NULL,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`EDP_ID`),
  KEY `FK79A4F8A8B18C01F` (`EDP_CRED_ID`),
  KEY `FK79A4F8A1498B59A` (`EDP_ICA_ID`),
  KEY `FK79A4F8A55CEDF9E` (`EDP_PTY_ID`),
  KEY `FK79A4F8A8F93669` (`EDP_PRO_ID`),
  KEY `FK79A4F8A7FE685CE` (`EDP_PROXY_CRED_ID`),
  KEY `FK79A4F8A52D4BA68` (`EDP_TRA_ID`),
  KEY `ETR_TB_ENDPOINT_CPA_TB_BU_FK1` (`EDP_BD_ID`),
  CONSTRAINT `FK79A4F8A52D4BA68` FOREIGN KEY (`EDP_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`),
  CONSTRAINT `FK79A4F8A1498B59A` FOREIGN KEY (`EDP_ICA_ID`) REFERENCES `ETR_TB_INTERCHANGE_AGR` (`ICA_ID`),
  CONSTRAINT `FK79A4F8A55CEDF9E` FOREIGN KEY (`EDP_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FK79A4F8A7FE685CE` FOREIGN KEY (`EDP_PROXY_CRED_ID`) REFERENCES `ETR_TB_CREDENTIALS` (`CRED_ID`),
  CONSTRAINT `FK79A4F8A8B18C01F` FOREIGN KEY (`EDP_CRED_ID`) REFERENCES `ETR_TB_CREDENTIALS` (`CRED_ID`),
  CONSTRAINT `FK79A4F8A8F93669` FOREIGN KEY (`EDP_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`),
  CONSTRAINT `ETR_TB_ENDPOINT_CPA_TB_BU_FK1` FOREIGN KEY (`EDP_BD_ID`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_ENDPOINT_AMQP` (
	`ID` bigint(20) NOT NULL AUTO_INCREMENT, 
	`EDP_AMQP_PROV_URL` varchar(255),
	PRIMARY KEY (`ID`),
	CONSTRAINT `FK_EDPAMQP_EDP` FOREIGN KEY (`ID`) REFERENCES `ETR_TB_ENDPOINT` (`EDP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_ENDPOINT_JMS` (
  `EDP_JMS_CFACT_NM` varchar(255) DEFAULT NULL,
  `EDP_JMS_DEST_JNDI_NM` varchar(255) NOT NULL,
  `EDP_JMS_INIT_CONT_FACT` varchar(255) DEFAULT NULL,
  `EDP_JMS_MESS_CON_CLASS` varchar(255) DEFAULT NULL,
  `EDP_JMS_PROV_URL` varchar(255) DEFAULT NULL,
  `ID` bigint(20) NOT NULL,
  `EDP_REPLY_TO_FLAG` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKB9FC93B79F3B3F3` (`ID`),
  CONSTRAINT `FKB9FC93B79F3B3F3` FOREIGN KEY (`ID`) REFERENCES `ETR_TB_ENDPOINT` (`EDP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_ENDPOINT_WS` (
  `EDP_WS_REQUIRE_SIGNED_RESP_FL` tinyint(1) NOT NULL,
  `EDP_WS_SING_FL` tinyint(1) NOT NULL,
  `EDP_WS_URL` varchar(255) NOT NULL,
  `ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FKBE4F7BB179F3B3F3` (`ID`),
  CONSTRAINT `FKBE4F7BB179F3B3F3` FOREIGN KEY (`ID`) REFERENCES `ETR_TB_ENDPOINT` (`EDP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_EXTRACTION_CONFIG` (
  `DE_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `DE_KEY` varchar(255) NOT NULL,
  `DE_XPATH` varchar(255) NOT NULL,
  `TRA_DOC_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`DE_ID`),
  KEY `FKB526E84568C364D4` (`TRA_DOC_ID`),
  CONSTRAINT `FKB526E84568C364D4` FOREIGN KEY (`TRA_DOC_ID`) REFERENCES `ETR_TB_DOCUMENT` (`DOC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PARTY_ROLE` (
  `PAR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `PAR_PTY_ID` bigint(20) DEFAULT NULL,
  `PAR_ROL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PAR_ID`),
  UNIQUE KEY `PAR_PTY_ID` (`PAR_PTY_ID`,`PAR_ROL_ID`),
  KEY `FK16247304E7EBC8AE` (`PAR_PTY_ID`),
  KEY `FK1624730471DB20FA` (`PAR_ROL_ID`),
  CONSTRAINT `FK1624730471DB20FA` FOREIGN KEY (`PAR_ROL_ID`) REFERENCES `ETR_TB_ROLE` (`ROL_ID`),
  CONSTRAINT `FK16247304E7EBC8AE` FOREIGN KEY (`PAR_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_ICA_PARTYROLE` (
  `ICA_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `PAR_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ICA_ID`,`PAR_ID`),
  KEY `FK87E5F78F69D5FD3A` (`PAR_ID`),
  KEY `FK87E5F78FB4F0194C` (`ICA_ID`),
  CONSTRAINT `FK87E5F78FB4F0194C` FOREIGN KEY (`ICA_ID`) REFERENCES `ETR_TB_INTERCHANGE_AGR` (`ICA_ID`),
  CONSTRAINT `FK87E5F78F69D5FD3A` FOREIGN KEY (`PAR_ID`) REFERENCES `ETR_TB_PARTY_ROLE` (`PAR_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MESSAGE` (
  `MSG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `MSG_CORRELATION_ID` varchar(255) DEFAULT NULL,
  `MSG_DOCUMENT_ID` varchar(300) NOT NULL,
  `MSG_ISSUE_DT` datetime DEFAULT NULL,
  `MSG_DOC_TYPE_CD` varchar(255) NOT NULL,
  `MSG_RECEIPT_DT` datetime DEFAULT NULL,
  `MSG_RSP_CD` varchar(255) DEFAULT NULL,
  `MSG_RETRIEVED_FL` tinyint(1) DEFAULT NULL,
  `MSG_STS_CD` varchar(255) DEFAULT NULL,
  `MSG_AGR_ID` bigint(20) DEFAULT NULL,
  `MSG_ISSUER_ID` bigint(20) NOT NULL,
  `MSG_RECEIVER_ID` bigint(20) DEFAULT NULL,
  `MSG_SENDER_ID` bigint(20) NOT NULL,
  `MSG_TRANS_ID` bigint(20) NOT NULL,
  `MSG_RETRIEVED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`MSG_ID`),
  KEY `FK2D8EB752B2957F25` (`MSG_AGR_ID`),
  KEY `FK2D8EB752CD5931CE` (`MSG_ISSUER_ID`),
  KEY `FK2D8EB7523DCBBE58` (`MSG_RECEIVER_ID`),
  KEY `FK2D8EB752C43388D2` (`MSG_SENDER_ID`),
  KEY `FK2D8EB752EB6FFDF3` (`MSG_TRANS_ID`),
  CONSTRAINT `FK2D8EB752EB6FFDF3` FOREIGN KEY (`MSG_TRANS_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`),
  CONSTRAINT `FK2D8EB7523DCBBE58` FOREIGN KEY (`MSG_RECEIVER_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FK2D8EB752B2957F25` FOREIGN KEY (`MSG_AGR_ID`) REFERENCES `ETR_TB_INTERCHANGE_AGR` (`ICA_ID`),
  CONSTRAINT `FK2D8EB752C43388D2` FOREIGN KEY (`MSG_SENDER_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FK2D8EB752CD5931CE` FOREIGN KEY (`MSG_ISSUER_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MESSAGE_PRIORITY` (
	`MP_ID` bigint(20) NOT NULL AUTO_INCREMENT, 
	`MP_SENDER_ID` bigint(20), 
	`MP_TRANS_ID` bigint(20), 
	`MP_PRIORITY` tinyint(1), 
	`CRE_ID` varchar(255), 
	`CRE_DT` datetime, 
	`MOD_ID` varchar(255), 
	`MOD_DT` datetime,
	PRIMARY KEY (`MP_ID`),
  CONSTRAINT `FK_MP_TRANS` FOREIGN KEY (`MP_TRANS_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`),
  CONSTRAINT `FK_MP_SENDER` FOREIGN KEY (`MP_SENDER_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)	
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MSG_BIN_VALUE` (
	`MSG_BIN_VAL_ID` bigint(20) AUTO_INCREMENT, 
	`MSG_BIN_VAL_VALUE` longblob, 
	 PRIMARY KEY (`MSG_BIN_VAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MESSAGE_BINARY` (
  `MSG_BIN_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `MSG_BIN_TYPE` varchar(255) DEFAULT NULL,
  `MSG_BIN_FILE_ID` varchar(255) DEFAULT NULL,
  `MSG_BIN_MIME` varchar(255) DEFAULT NULL,
  `MSG_BIN_SIZE` bigint(20) DEFAULT NULL,
  `MSG_BIN_MSG_ID` bigint(20) DEFAULT NULL,
  `IV` TINYBLOB,
  `MSG_BIN_MSG_BIN_VAL_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MSG_BIN_ID`),
  UNIQUE KEY `MSG_BIN_FILE_ID` (`MSG_BIN_FILE_ID`),
  KEY `FK6A1EC58E319BB8DB` (`MSG_BIN_MSG_ID`),
  CONSTRAINT `FK6A1EC58E319BB8DB` FOREIGN KEY (`MSG_BIN_MSG_ID`) REFERENCES `ETR_TB_MESSAGE` (`MSG_ID`),
  CONSTRAINT `FK_MSG_BIN_MSG_BIN_VAL` FOREIGN KEY (`MSG_BIN_MSG_BIN_VAL_ID`) REFERENCES `ETR_TB_MSG_BIN_VALUE` (`MSG_BIN_VAL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MESSAGE_ROUTING` (
  `MR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `MR_ENDPOINT_ID` bigint(20) DEFAULT NULL,
  `MR_MESSAGE_ID` bigint(20) DEFAULT NULL,
  `MR_PROCESSED_FLAG` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`MR_ID`),
  KEY `ETR_FK_MR_ENDPOINT_ID` (`MR_ENDPOINT_ID`),
  KEY `ETR_FK_MR_MESSAGE_ID` (`MR_MESSAGE_ID`),
  CONSTRAINT `ETR_FK_MR_ENDPOINT_ID` FOREIGN KEY (`MR_ENDPOINT_ID`) REFERENCES `ETR_TB_ENDPOINT` (`EDP_ID`),
  CONSTRAINT `ETR_FK_MR_MESSAGE_ID` FOREIGN KEY (`MR_MESSAGE_ID`) REFERENCES `ETR_TB_MESSAGE` (`MSG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_METADATA` (
  `MD_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `MD_TYPE` varchar(255) DEFAULT NULL,
  `MD_VALUE` longtext,
  `PID_DOC_ID` bigint(20) DEFAULT NULL,
  `PID_ICA_ID` bigint(20) DEFAULT NULL,
  `PID_PRO_ID` bigint(20) DEFAULT NULL,
  `PID_TRA_ID` bigint(20) DEFAULT NULL,
  `MD_SENDER_ID` bigint(20) DEFAULT NULL,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,  
  `MD_BUSINESSDOMAIN_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`MD_ID`),
  KEY `FK8500AD2498D93FEC` (`PID_DOC_ID`),
  KEY `FK8500AD249A88A280` (`PID_ICA_ID`),
  KEY `FK8500AD248EE9234F` (`PID_PRO_ID`),
  KEY `FK8500AD24D8C4A74E` (`PID_TRA_ID`),
  KEY `FK_MD_PTY` (MD_SENDER_ID),
  CONSTRAINT `FK8500AD24D8C4A74E` FOREIGN KEY (`PID_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`),
  CONSTRAINT `FK8500AD248EE9234F` FOREIGN KEY (`PID_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`),
  CONSTRAINT `FK8500AD2498D93FEC` FOREIGN KEY (`PID_DOC_ID`) REFERENCES `ETR_TB_DOCUMENT` (`DOC_ID`),
  CONSTRAINT `FK8500AD249A88A280` FOREIGN KEY (`PID_ICA_ID`) REFERENCES `ETR_TB_INTERCHANGE_AGR` (`ICA_ID`),
  CONSTRAINT `FK_MD_PTY` FOREIGN KEY (`MD_SENDER_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FK_METADATA_BD_FK` FOREIGN KEY (`MD_BUSINESSDOMAIN_ID`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MONITORING_QUERY` (
	`MON_ID` bigint(20)  NOT NULL AUTO_INCREMENT, 
	`MON_QUERY` varchar(2000),
	PRIMARY KEY (`MON_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MSG_MSG` (
  `MSG_CHILD_ID` bigint(20) NOT NULL,
  `MSG_PAR_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`MSG_CHILD_ID`,`MSG_PAR_ID`),
  KEY `FK44CF18EEFECAF083` (`MSG_PAR_ID`),
  KEY `FK44CF18EEA4F6EA8` (`MSG_CHILD_ID`),
  CONSTRAINT `FK44CF18EEA4F6EA8` FOREIGN KEY (`MSG_CHILD_ID`) REFERENCES `ETR_TB_MESSAGE` (`MSG_ID`),
  CONSTRAINT `FK44CF18EEFECAF083` FOREIGN KEY (`MSG_PAR_ID`) REFERENCES `ETR_TB_MESSAGE` (`MSG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_MSG_RESPONSE_CODE` (
  `RSC_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `RSC_CD` varchar(255) NOT NULL,
  `RSC_VAL` varchar(255) NOT NULL,
  `RSC_STS_CD` varchar(255) DEFAULT NULL,
  `RSC_DOC_ID` bigint(20) DEFAULT NULL,
  `RSC_ICA_ID` bigint(20) DEFAULT NULL,
  `RSC_PRO_ID` bigint(20) DEFAULT NULL,
  `RSC_TRA_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`RSC_ID`),
  KEY `FK436AFC78E4374B55` (`RSC_DOC_ID`),
  KEY `FK436AFC78E5E6ADE9` (`RSC_ICA_ID`),
  KEY `FK436AFC78DA472EB8` (`RSC_PRO_ID`),
  KEY `FK436AFC782422B2B7` (`RSC_TRA_ID`),
  CONSTRAINT `FK436AFC782422B2B7` FOREIGN KEY (`RSC_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`),
  CONSTRAINT `FK436AFC78DA472EB8` FOREIGN KEY (`RSC_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`),
  CONSTRAINT `FK436AFC78E4374B55` FOREIGN KEY (`RSC_DOC_ID`) REFERENCES `ETR_TB_DOCUMENT` (`DOC_ID`),
  CONSTRAINT `FK436AFC78E5E6ADE9` FOREIGN KEY (`RSC_ICA_ID`) REFERENCES `ETR_TB_INTERCHANGE_AGR` (`ICA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PARTY_ID` (
  `PID_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `PID_IDENTIFIER_SCHEME` varchar(255) DEFAULT NULL,
  `PID_IDENTIFIER_VALUE` varchar(255) DEFAULT NULL,
  `PID_PTY_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`PID_ID`),
  KEY `FKE6B74F29DBBECC84` (`PID_PTY_ID`),
  CONSTRAINT `FKE6B74F29DBBECC84` FOREIGN KEY (`PID_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PARTYAGREEMENT` (
  `PAG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `PAG_AUTH_PTY_ID` bigint(20) NOT NULL,
  `PAG_DEL_PTY_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PAG_ID`),
  KEY `FK751E3419C0F7139E` (`PAG_AUTH_PTY_ID`),
  KEY `FK751E3419E04AB54D` (`PAG_DEL_PTY_ID`),
  CONSTRAINT `FK751E3419E04AB54D` FOREIGN KEY (`PAG_DEL_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FK751E3419C0F7139E` FOREIGN KEY (`PAG_AUTH_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PARTYAGREEMENT_TRAN` (
  `PAT_PAG_ID` bigint(20) NOT NULL,
  `PAT_TRA_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PAT_PAG_ID`,`PAT_TRA_ID`),
  KEY `FKF9AD9791B4B3FD36` (`PAT_TRA_ID`),
  KEY `FKF9AD97919E1BEE1F` (`PAT_PAG_ID`),
  CONSTRAINT `FKF9AD97919E1BEE1F` FOREIGN KEY (`PAT_PAG_ID`) REFERENCES `ETR_TB_PARTYAGREEMENT` (`PAG_ID`),
  CONSTRAINT `FKF9AD9791B4B3FD36` FOREIGN KEY (`PAT_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_PROFILE_TRANSACTION` (
  `PTR_PRO_ID` bigint(20) NOT NULL,
  `PTR_TRA_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`PTR_PRO_ID`,`PTR_TRA_ID`),
  KEY `FK189537F3E605E08B` (`PTR_TRA_ID`),
  KEY `FK189537F39C2A5C8C` (`PTR_PRO_ID`),
  CONSTRAINT `FK189537F39C2A5C8C` FOREIGN KEY (`PTR_PRO_ID`) REFERENCES `ETR_TB_PROFILE` (`PRO_ID`),
  CONSTRAINT `FK189537F3E605E08B` FOREIGN KEY (`PTR_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_QUERY_RESULT` (
  `QR_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `QR_KEY` varchar(255) NOT NULL,
  `QR_VALUE` varchar(255) NOT NULL,
  `QR_MSG_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`QR_ID`),
  KEY `FK37964B094583F303` (`QR_MSG_ID`),
  CONSTRAINT `FK37964B094583F303` FOREIGN KEY (`QR_MSG_ID`) REFERENCES `ETR_TB_MESSAGE` (`MSG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_XML_STORE` (
  `XS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `XS_KEY` varchar(255) NOT NULL,
  `XS_VALUE` longtext,
  PRIMARY KEY (`XS_ID`),
  UNIQUE KEY `XS_KEY` (`XS_KEY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_LOG` (
  `LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CRE_DT` datetime DEFAULT NULL,
  `CRE_ID` varchar(255) DEFAULT NULL,
  `MOD_DT` datetime DEFAULT NULL,
  `MOD_ID` varchar(255) DEFAULT NULL,
  `LOG_BUS_CORRELATION_ID` varchar(255) DEFAULT NULL,
  `LOG_CORRELATION_ID` varchar(255) DEFAULT NULL,
  `LOG_DESCRIPTION` varchar(1000) DEFAULT NULL,
  `LOG_DOCUMENT_ID` varchar(300) DEFAULT NULL,
  `LOG_DOCUMENT_TYPE_CD` varchar(255) DEFAULT NULL,
  `LOG_LARGE_VALUE` longtext,
  `LOG_TYPE` varchar(255) NOT NULL,
  `LOG_MSG_BIN_ID` bigint(20) DEFAULT NULL,
  `LOG_MSG_ID` bigint(20) DEFAULT NULL,
  `LOG_MSG_SIZE` bigint(20) DEFAULT NULL,
  `LOG_OPERATION` varchar(255) DEFAULT NULL,
  `LOG_URL_CONTEXT` varchar(255) DEFAULT NULL,
  `LOG_VALUE` varchar(255) DEFAULT NULL,
  `LOG_BUSINESS_DOMAIN` bigint(20) DEFAULT NULL,
  `LOG_ISSUER_PTY_ID` bigint(20) DEFAULT NULL,
  `LOG_RECEIVER_PTY_ID` bigint(20) DEFAULT NULL,
  `LOG_SENDER_PTY_ID` bigint(20) DEFAULT NULL,
  `LOG_TRA_ID` bigint(20) DEFAULT NULL,
  `LOG_MODULE` varchar(255) DEFAULT NULL,
  `LOG_USRNAME` varchar(255) DEFAULT NULL,
  `LOG_USR_ROLE` varchar(255) DEFAULT NULL,
  `LOG_AUTH_IP_ADDRESS` varchar(255) DEFAULT NULL,
  `LOG_ENTITY` varchar(255) DEFAULT NULL,
  `LOG_ENITITY_ID` bigint(20) DEFAULT NULL,
  `LOG_CLASS` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`LOG_ID`),
  KEY `FKF8F5C00F2C4C93E6` (`LOG_BUSINESS_DOMAIN`),
  KEY `FKF8F5C00FF83269DB` (`LOG_ISSUER_PTY_ID`),
  KEY `FKF8F5C00F93170CA5` (`LOG_RECEIVER_PTY_ID`),
  KEY `FKF8F5C00FBC419EDF` (`LOG_SENDER_PTY_ID`),
  KEY `FKF8F5C00FB8DD0375` (`LOG_TRA_ID`),
  CONSTRAINT `FKF8F5C00FB8DD0375` FOREIGN KEY (`LOG_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`),
  CONSTRAINT `FKF8F5C00F2C4C93E6` FOREIGN KEY (`LOG_BUSINESS_DOMAIN`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`),
  CONSTRAINT `FKF8F5C00F93170CA5` FOREIGN KEY (`LOG_RECEIVER_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FKF8F5C00FBC419EDF` FOREIGN KEY (`LOG_SENDER_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`),
  CONSTRAINT `FKF8F5C00FF83269DB` FOREIGN KEY (`LOG_ISSUER_PTY_ID`) REFERENCES `ETR_TB_PARTY` (`PTY_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_SERVICE_ENDPOINT` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_SERVICE_EP_TRANSACTION` (
  `ENDPOINT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TRANSACTION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ENDPOINT_ID`,`TRANSACTION_ID`),
  KEY `FKF273554963023EFF` (`TRANSACTION_ID`),
  KEY `FKF2735549D9794AF4` (`ENDPOINT_ID`),
  CONSTRAINT `FKF2735549D9794AF4` FOREIGN KEY (`ENDPOINT_ID`) REFERENCES `ETR_TB_SERVICE_ENDPOINT` (`ID`),
  CONSTRAINT `FKF273554963023EFF` FOREIGN KEY (`TRANSACTION_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ETR_TB_HR_TEMPLATE` ( 
   	`HRT_ID` bigint(20) NOT NULL AUTO_INCREMENT, 
	`CRE_DT` datetime, 
	`CRE_ID` varchar(255), 
	`MOD_DT` datetime, 
	`MOD_ID` varchar(255), 
	`HRT_NAME` varchar(255), 
	`HRT_XSLT` longtext, 
	`HRT_DOC_ID` bigint(20), 
	`HRT_TRA_ID` bigint(20), 
	`HRT_IS_DEFAULT` tinyint(1) DEFAULT 0,
	PRIMARY KEY (`HRT_ID`),
	UNIQUE KEY `HRT_UNIQUE` (`HRT_NAME`, `HRT_DOC_ID`, `HRT_TRA_ID`),
	CONSTRAINT `FK_HR_TEMPLATE_TX` FOREIGN KEY (`HRT_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`), 
	CONSTRAINT `FK_HR_TEMPLATE_DOC` FOREIGN KEY (`HRT_DOC_ID`) REFERENCES `ETR_TB_DOCUMENT` (`DOC_ID`),
	KEY `HRT_IDX` (`HRT_NAME`, `HRT_DOC_ID`, `HRT_TRA_ID`)
   ) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `ETR_TB_POLICY` (
	`POL_ID` bigint(20) NOT NULL AUTO_INCREMENT, 
	`CRE_DT` datetime, 
	`CRE_ID` varchar(255), 
	`MOD_DT` datetime, 
	`MOD_ID` varchar(255), 
	`POL_ACTIVE_FLAG` tinyint(1), 
	`POL_TRA_ID` bigint(20), 
	`POL_BD_ID` bigint(20), 
	`POL_TYPE` varchar(20), 
	`POL_FREQUENCY` varchar(20), 
	`POL_VALUE` bigint(20), 
	`POL_FLEXIBILITY` smallint, 
	 PRIMARY KEY (`POL_ID`),
	 CONSTRAINT `FK_POLICY_TX` FOREIGN KEY (`POL_TRA_ID`) REFERENCES `ETR_TB_TRANSACTION` (`TRA_ID`), 
	 CONSTRAINT `FK_POLICY_BD` FOREIGN KEY (`POL_BD_ID`) REFERENCES `CPA_TB_BUSINESS_DOMAIN` (`CBD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_JOB_DETAILS` (
   	`SCHED_NAME` varchar(120), 
	`JOB_NAME` varchar(200), 
	`JOB_GROUP` varchar(200), 
	`DESCRIPTION` varchar(250), 
	`JOB_CLASS_NAME` varchar(250), 
	`IS_DURABLE` varchar(1), 
	`IS_NONCONCURRENT` varchar(1), 
	`IS_UPDATE_DATA` varchar(1), 
	`REQUESTS_RECOVERY` varchar(1), 
	`JOB_DATA` BLOB, 
	PRIMARY KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `ET2_IDX_QRTZ_J_GRP` (`SCHED_NAME`, `JOB_GROUP`),
	KEY `ET2_IDX_QRTZ_J_REQ_RECOVERY` (`SCHED_NAME`, `REQUESTS_RECOVERY`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`JOB_NAME` varchar(200), 
	`JOB_GROUP` varchar(200), 
	`DESCRIPTION` varchar(250), 
	`NEXT_FIRE_TIME` bigint(13), 
	`PREV_FIRE_TIME` bigint(13), 
	`PRIORITY` bigint(13), 
	`TRIGGER_STATE` varchar(16), 
	`TRIGGER_TYPE` varchar(8), 
	`START_TIME` bigint(13), 
	`END_TIME` bigint(13), 
	`CALENDAR_NAME` varchar(200), 
	`MISFIRE_INSTR` tinyint(2), 
	`JOB_DATA` longblob, 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
	CONSTRAINT `FK2_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`) REFERENCES `QRTZ2_JOB_DETAILS` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_T_C` (`SCHED_NAME`, `CALENDAR_NAME`),
	KEY `IDX_QRTZ2_T_G` (`SCHED_NAME`, `TRIGGER_GROUP`),
	KEY `IDX_QRTZ2_T_J` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_T_JG` (`SCHED_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_T_NEXT_FIRE_TIME` (`SCHED_NAME`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_MISFIRE` (`SCHED_NAME`, `MISFIRE_INSTR`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_ST` (`SCHED_NAME`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_ST_MISFIRE` (`SCHED_NAME`, `MISFIRE_INSTR`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`),
	KEY `IDX_QRTZ2_T_NFT_ST_MISFIRE_GRP` (`SCHED_NAME`, `MISFIRE_INSTR`, `TRIGGER_STATE`, `NEXT_FIRE_TIME`, `TRIGGER_GROUP`), 
	KEY `IDX_QRTZ2_T_N_G_STATE` (`SCHED_NAME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
	KEY `IDX_QRTZ2_T_N_STATE` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`, `TRIGGER_STATE`),
	KEY `IDX_QRTZ2_T_STATE` (`SCHED_NAME`, `TRIGGER_STATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	

CREATE TABLE `QRTZ2_BLOB_TRIGGERS` ( 
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`BLOB_DATA` longblob, 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
	CONSTRAINT `FK2_BLOB_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ2_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_CALENDARS` (
   	`SCHED_NAME` varchar(120), 
	`CALENDAR_NAME` varchar(200), 
	`CALENDAR` BLOB, 
	PRIMARY KEY (`SCHED_NAME`, `CALENDAR_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_CRON_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`CRON_EXPRESSION` varchar(120), 
	`TIME_ZONE_ID` varchar(80), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`),
	CONSTRAINT `FK2_CRON_TRIGGERS` FOREIGN KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`) REFERENCES `QRTZ2_TRIGGERS` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_FIRED_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`ENTRY_ID` varchar(95), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`INSTANCE_NAME` varchar(200), 
	`FIRED_TIME` bigint(13), 
	`SCHED_TIME` bigint(13), 
	`PRIORITY` bigint(13), 
	`STATE` varchar(16), 
	`JOB_NAME` varchar(200), 
	`JOB_GROUP` varchar(200), 
	`IS_NONCONCURRENT` varchar(1), 
	`REQUESTS_RECOVERY` varchar(1), 
	PRIMARY KEY (`SCHED_NAME`, `ENTRY_ID`),
	KEY `IDX_QRTZ2_FT_JG` (`SCHED_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_FT_J_G` (`SCHED_NAME`, `JOB_NAME`, `JOB_GROUP`),
	KEY `IDX_QRTZ2_FT_RCVRY` (`SCHED_NAME`, `INSTANCE_NAME`, `REQUESTS_RECOVERY`),
	KEY `IDX_QRTZ2_FT_TG` (`SCHED_NAME`, `TRIGGER_GROUP`),
	KEY `IDX_QRTZ2_FT_TRIG_INST_NAME` (`SCHED_NAME`, `INSTANCE_NAME`),
	KEY `IDX_QRTZ2_FT_T_G` (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_LOCKS` (
  	`SCHED_NAME` varchar(120), 
	`LOCK_NAME` varchar(40), 
	 PRIMARY KEY (`SCHED_NAME`, `LOCK_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;	 

CREATE TABLE `QRTZ2_PAUSED_TRIGGER_GRPS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_GROUP` varchar(200), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_SCHEDULER_STATE` (
   	`SCHED_NAME` varchar(120), 
	`INSTANCE_NAME` varchar(200), 
	`LAST_CHECKIN_TIME` bigint(13), 
	`CHECKIN_INTERVAL` bigint(13), 
	PRIMARY KEY (`SCHED_NAME`, `INSTANCE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_SIMPLE_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`REPEAT_COUNT` int, 
	`REPEAT_INTERVAL` bigint(12), 
	`TIMES_TRIGGERED` bigint(10), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `QRTZ2_SIMPROP_TRIGGERS` (
   	`SCHED_NAME` varchar(120), 
	`TRIGGER_NAME` varchar(200), 
	`TRIGGER_GROUP` varchar(200), 
	`STR_PROP_1` varchar(512), 
	`STR_PROP_2` varchar(512), 
	`STR_PROP_3` varchar(512), 
	`INT_PROP_1` bigint(10), 
	`INT_PROP_2` bigint(10), 
	`LONG_PROP_1` bigint(13), 
	`LONG_PROP_2` bigint(13), 
	`DEC_PROP_1` decimal(13,4), 
	`DEC_PROP_2` decimal(13,4), 
	`BOOL_PROP_1` varchar(1), 
	`BOOL_PROP_2` varchar(1), 
	PRIMARY KEY (`SCHED_NAME`, `TRIGGER_NAME`, `TRIGGER_GROUP`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;