//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.26 at 05:11:11 PM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.payload.edma;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subject" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="reqForInfoNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fileNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inAttentionOf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="inboundDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="outboundMetaData" type="{urn:eu:europa:ec:comp:etrustex}ETrustExEdmaMdOutbound"/>
 *         &lt;element name="inboundMetaData" type="{urn:eu:europa:ec:comp:etrustex}ETrustExEdmaMdInbound"/>
 *         &lt;element name="outboundDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "subject",
        "reqForInfoNumber",
        "fileNumber",
        "inAttentionOf",
        "inboundDate",
        "language",
        "outboundMetaData",
        "inboundMetaData",
        "outboundDate",
        "comment"
})
@XmlRootElement(name = "ETrustExEdmaMd")
public class ETrustExEdmaMd {

    @XmlElement(required = true)
    protected String subject;
    @XmlElement(required = true)
    protected String reqForInfoNumber;
    @XmlElement(required = true)
    protected String fileNumber;
    @XmlElement(required = true)
    protected String inAttentionOf;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar inboundDate;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(required = true)
    protected ETrustExEdmaMdOutbound outboundMetaData;
    @XmlElement(required = true)
    protected ETrustExEdmaMdInbound inboundMetaData;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar outboundDate;
    @XmlElement(required = true)
    protected String comment;

    /**
     * Gets the value of the subject property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the reqForInfoNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReqForInfoNumber() {
        return reqForInfoNumber;
    }

    /**
     * Sets the value of the reqForInfoNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReqForInfoNumber(String value) {
        this.reqForInfoNumber = value;
    }

    /**
     * Gets the value of the fileNumber property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * Sets the value of the fileNumber property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFileNumber(String value) {
        this.fileNumber = value;
    }

    /**
     * Gets the value of the inAttentionOf property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInAttentionOf() {
        return inAttentionOf;
    }

    /**
     * Sets the value of the inAttentionOf property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInAttentionOf(String value) {
        this.inAttentionOf = value;
    }

    /**
     * Gets the value of the inboundDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getInboundDate() {
        return inboundDate;
    }

    /**
     * Sets the value of the inboundDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setInboundDate(XMLGregorianCalendar value) {
        this.inboundDate = value;
    }

    /**
     * Gets the value of the language property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the outboundMetaData property.
     *
     * @return possible object is
     * {@link ETrustExEdmaMdOutbound }
     */
    public ETrustExEdmaMdOutbound getOutboundMetaData() {
        return outboundMetaData;
    }

    /**
     * Sets the value of the outboundMetaData property.
     *
     * @param value allowed object is
     *              {@link ETrustExEdmaMdOutbound }
     */
    public void setOutboundMetaData(ETrustExEdmaMdOutbound value) {
        this.outboundMetaData = value;
    }

    /**
     * Gets the value of the inboundMetaData property.
     *
     * @return possible object is
     * {@link ETrustExEdmaMdInbound }
     */
    public ETrustExEdmaMdInbound getInboundMetaData() {
        return inboundMetaData;
    }

    /**
     * Sets the value of the inboundMetaData property.
     *
     * @param value allowed object is
     *              {@link ETrustExEdmaMdInbound }
     */
    public void setInboundMetaData(ETrustExEdmaMdInbound value) {
        this.inboundMetaData = value;
    }

    /**
     * Gets the value of the outboundDate property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getOutboundDate() {
        return outboundDate;
    }

    /**
     * Sets the value of the outboundDate property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setOutboundDate(XMLGregorianCalendar value) {
        this.outboundDate = value;
    }

    /**
     * Gets the value of the comment property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setComment(String value) {
        this.comment = value;
    }

}
