//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.26 at 05:11:11 PM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.payload.edma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ETrustExEdmaMdDocument complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ETrustExEdmaMdDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="confidential" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="documentComment" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ETrustExEdmaMdDocument", propOrder = {
        "confidential",
        "documentComment",
        "file",
        "fileReferenceId",
        "path"
})
public class ETrustExEdmaMdDocument {

    @XmlElement(required = true)
    protected String confidential;
    @XmlElement(required = true)
    protected String documentComment;
    @XmlElement(required = true)
    protected String file;
    @XmlElement(required = true)
    protected String path;
    @XmlElement(required = true)
    protected String fileReferenceId;

    /**
     * Gets the value of the confidential property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConfidential() {
        return confidential;
    }

    /**
     * Sets the value of the confidential property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConfidential(String value) {
        this.confidential = value;
    }

    /**
     * Gets the value of the documentComment property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDocumentComment() {
        return documentComment;
    }

    /**
     * Sets the value of the documentComment property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDocumentComment(String value) {
        this.documentComment = value;
    }

    /**
     * Gets the value of the file property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFile(String value) {
        this.file = value;
    }

    /**
     * Gets the value of the path property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Gets the value of the fileReferenceId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFileReferenceId() {
        return fileReferenceId;
    }

    /**
     * Sets the value of the fileReferenceId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFileReferenceId(String fileReferenceId) {
        this.fileReferenceId = fileReferenceId;
    }

}
