//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.26 at 05:11:11 PM CEST 
//


package eu.europa.ec.etrustex.webaccess.web.payload.edma;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ETrustExEdmaMdInbound complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ETrustExEdmaMdInbound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transferStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{urn:eu:europa:ec:comp:etrustex}documents"/>
 *         &lt;element name="onBehalfOf" type="{urn:eu:europa:ec:comp:etrustex}ETrustExEdmaMdCompany"/>
 *         &lt;element name="sender" type="{urn:eu:europa:ec:comp:etrustex}ETrustExEdmaMdCompany"/>
 *         &lt;element name="eMail" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="from" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="yourReference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="instrument" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ETrustExEdmaMdInbound", propOrder = {
        "transferStatus",
        "documents",
        "onBehalfOf",
        "sender",
        "eMail",
        "from",
        "yourReference",
        "instrument",
        "distributionList"
})
public class ETrustExEdmaMdInbound {

    @XmlElement(required = true)
    protected String transferStatus;
    @XmlElement(required = true)
    protected Documents documents;
    @XmlElement(required = true)
    protected ETrustExEdmaMdCompany onBehalfOf;
    @XmlElement(required = true)
    protected ETrustExEdmaMdCompany sender;
    @XmlElement(required = true)
    protected String eMail;
    @XmlElement(required = true)
    protected String from;
    @XmlElement(required = true)
    protected String yourReference;
    @XmlElement(required = true)
    protected String instrument;
    @XmlElement(required = true)
    protected String distributionList;

    /**
     * Gets the value of the transferStatus property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTransferStatus() {
        return transferStatus;
    }

    /**
     * Sets the value of the transferStatus property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTransferStatus(String value) {
        this.transferStatus = value;
    }

    /**
     * Gets the value of the documents property.
     *
     * @return possible object is
     * {@link Documents }
     */
    public Documents getDocuments() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     *
     * @param value allowed object is
     *              {@link Documents }
     */
    public void setDocuments(Documents value) {
        this.documents = value;
    }

    /**
     * Gets the value of the onBehalfOf property.
     *
     * @return possible object is
     * {@link ETrustExEdmaMdCompany }
     */
    public ETrustExEdmaMdCompany getOnBehalfOf() {
        return onBehalfOf;
    }

    /**
     * Sets the value of the onBehalfOf property.
     *
     * @param value allowed object is
     *              {@link ETrustExEdmaMdCompany }
     */
    public void setOnBehalfOf(ETrustExEdmaMdCompany value) {
        this.onBehalfOf = value;
    }

    /**
     * Gets the value of the sender property.
     *
     * @return possible object is
     * {@link ETrustExEdmaMdCompany }
     */
    public ETrustExEdmaMdCompany getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     *
     * @param value allowed object is
     *              {@link ETrustExEdmaMdCompany }
     */
    public void setSender(ETrustExEdmaMdCompany value) {
        this.sender = value;
    }

    /**
     * Gets the value of the eMail property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

    /**
     * Gets the value of the from property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the yourReference property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getYourReference() {
        return yourReference;
    }

    /**
     * Sets the value of the yourReference property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setYourReference(String value) {
        this.yourReference = value;
    }

    /**
     * Gets the value of the instrument property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getInstrument() {
        return instrument;
    }

    /**
     * Sets the value of the instrument property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInstrument(String value) {
        this.instrument = value;
    }

    /**
     * Gets the value of the distributionList property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getDistributionList() {
        return distributionList;
    }

    /**
     * Sets the value of the distributionList property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setDistributionList(String distributionList) {
        this.distributionList = distributionList;
    }

}
