ALTER TABLE "ETX_WEB_ATTACHMENT" RENAME COLUMN "ATT_CHECKSUM" TO "ATT_TRANSMISSION_CHK"
/
ALTER TABLE "ETX_WEB_ATTACHMENT" RENAME COLUMN "ATT_CHECKSUM_METHOD" TO "ATT_TRANSMISSION_CHK_METHOD"
/

