//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for abstract_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="abstract_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xhtml_r" type="{}xhtml_r_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "abstract_type", propOrder = {
    "xhtmlR"
})
public class AbstractType {

    @XmlElement(name = "xhtml_r", required = true)
    protected XhtmlRType xhtmlR;

    /**
     * Gets the value of the xhtmlR property.
     * 
     * @return
     *     possible object is
     *     {@link XhtmlRType }
     *     
     */
    public XhtmlRType getXhtmlR() {
        return xhtmlR;
    }

    /**
     * Sets the value of the xhtmlR property.
     * 
     * @param value
     *     allowed object is
     *     {@link XhtmlRType }
     *     
     */
    public void setXhtmlR(XhtmlRType value) {
        this.xhtmlR = value;
    }

}
