//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{}content_qual_base_group"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contentPriority",
    "contentCategoryR",
    "contentLifeCycle",
    "contentIpg"
})
@XmlRootElement(name = "content_qual")
public class ContentQual {

    @XmlElement(name = "content_priority")
    protected String contentPriority;
    @XmlElement(name = "content_category_r")
    protected ContentQual.ContentCategoryR contentCategoryR;
    @XmlElement(name = "content_life_cycle", required = true)
    protected ContentQual.ContentLifeCycle contentLifeCycle;
    @XmlElement(name = "content_ipg", required = true)
    protected IpgMetaType contentIpg;

    /**
     * Gets the value of the contentPriority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentPriority() {
        return contentPriority;
    }

    /**
     * Sets the value of the contentPriority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentPriority(String value) {
        this.contentPriority = value;
    }

    /**
     * Gets the value of the contentCategoryR property.
     * 
     * @return
     *     possible object is
     *     {@link ContentQual.ContentCategoryR }
     *     
     */
    public ContentQual.ContentCategoryR getContentCategoryR() {
        return contentCategoryR;
    }

    /**
     * Sets the value of the contentCategoryR property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentQual.ContentCategoryR }
     *     
     */
    public void setContentCategoryR(ContentQual.ContentCategoryR value) {
        this.contentCategoryR = value;
    }

    /**
     * Gets the value of the contentLifeCycle property.
     * 
     * @return
     *     possible object is
     *     {@link ContentQual.ContentLifeCycle }
     *     
     */
    public ContentQual.ContentLifeCycle getContentLifeCycle() {
        return contentLifeCycle;
    }

    /**
     * Sets the value of the contentLifeCycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentQual.ContentLifeCycle }
     *     
     */
    public void setContentLifeCycle(ContentQual.ContentLifeCycle value) {
        this.contentLifeCycle = value;
    }

    /**
     * Gets the value of the contentIpg property.
     * 
     * @return
     *     possible object is
     *     {@link IpgMetaType }
     *     
     */
    public IpgMetaType getContentIpg() {
        return contentIpg;
    }

    /**
     * Sets the value of the contentIpg property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpgMetaType }
     *     
     */
    public void setContentIpg(IpgMetaType value) {
        this.contentIpg = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="content_category" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contentCategory"
    })
    public static class ContentCategoryR {

        @XmlElement(name = "content_category")
        protected List<String> contentCategory;

        /**
         * Gets the value of the contentCategory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the contentCategory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContentCategory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getContentCategory() {
            if (contentCategory == null) {
                contentCategory = new ArrayList<String>();
            }
            return this.contentCategory;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="clc_creation_date" type="{}date_type"/>
     *         &lt;element name="clc_modification_date" type="{}date_type"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clcCreationDate",
        "clcModificationDate"
    })
    public static class ContentLifeCycle {

        @XmlElement(name = "clc_creation_date", required = true)
        protected String clcCreationDate;
        @XmlElement(name = "clc_modification_date", required = true)
        protected String clcModificationDate;

        /**
         * Gets the value of the clcCreationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClcCreationDate() {
            return clcCreationDate;
        }

        /**
         * Sets the value of the clcCreationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClcCreationDate(String value) {
            this.clcCreationDate = value;
        }

        /**
         * Gets the value of the clcModificationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClcModificationDate() {
            return clcModificationDate;
        }

        /**
         * Sets the value of the clcModificationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClcModificationDate(String value) {
            this.clcModificationDate = value;
        }

    }

}
