//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for hd_heading_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hd_heading_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hd_short_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hd_long_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hd_abstract">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="xhtml_r">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}xhtml_r_type">
 *                           &lt;sequence>
 *                             &lt;element name="media" type="{}media_type" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="hd_media">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="media_reference" type="{}media_reference_type"/>
 *                   &lt;element name="media_alternative_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hd_heading_type", propOrder = {
    "hdShortTitle",
    "hdLongTitle",
    "hdAbstract",
    "hdMedia"
})
public class HdHeadingType {

    @XmlElement(name = "hd_short_title", required = true)
    protected String hdShortTitle;
    @XmlElement(name = "hd_long_title", required = true)
    protected String hdLongTitle;
    @XmlElement(name = "hd_abstract", required = true)
    protected HdHeadingType.HdAbstract hdAbstract;
    @XmlElement(name = "hd_media", required = true)
    protected HdHeadingType.HdMedia hdMedia;

    /**
     * Gets the value of the hdShortTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdShortTitle() {
        return hdShortTitle;
    }

    /**
     * Sets the value of the hdShortTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdShortTitle(String value) {
        this.hdShortTitle = value;
    }

    /**
     * Gets the value of the hdLongTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHdLongTitle() {
        return hdLongTitle;
    }

    /**
     * Sets the value of the hdLongTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHdLongTitle(String value) {
        this.hdLongTitle = value;
    }

    /**
     * Gets the value of the hdAbstract property.
     * 
     * @return
     *     possible object is
     *     {@link HdHeadingType.HdAbstract }
     *     
     */
    public HdHeadingType.HdAbstract getHdAbstract() {
        return hdAbstract;
    }

    /**
     * Sets the value of the hdAbstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link HdHeadingType.HdAbstract }
     *     
     */
    public void setHdAbstract(HdHeadingType.HdAbstract value) {
        this.hdAbstract = value;
    }

    /**
     * Gets the value of the hdMedia property.
     * 
     * @return
     *     possible object is
     *     {@link HdHeadingType.HdMedia }
     *     
     */
    public HdHeadingType.HdMedia getHdMedia() {
        return hdMedia;
    }

    /**
     * Sets the value of the hdMedia property.
     * 
     * @param value
     *     allowed object is
     *     {@link HdHeadingType.HdMedia }
     *     
     */
    public void setHdMedia(HdHeadingType.HdMedia value) {
        this.hdMedia = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="xhtml_r">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}xhtml_r_type">
     *                 &lt;sequence>
     *                   &lt;element name="media" type="{}media_type" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xhtmlR"
    })
    public static class HdAbstract {

        @XmlElement(name = "xhtml_r", required = true)
        protected HdHeadingType.HdAbstract.XhtmlR xhtmlR;

        /**
         * Gets the value of the xhtmlR property.
         * 
         * @return
         *     possible object is
         *     {@link HdHeadingType.HdAbstract.XhtmlR }
         *     
         */
        public HdHeadingType.HdAbstract.XhtmlR getXhtmlR() {
            return xhtmlR;
        }

        /**
         * Sets the value of the xhtmlR property.
         * 
         * @param value
         *     allowed object is
         *     {@link HdHeadingType.HdAbstract.XhtmlR }
         *     
         */
        public void setXhtmlR(HdHeadingType.HdAbstract.XhtmlR value) {
            this.xhtmlR = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}xhtml_r_type">
         *       &lt;sequence>
         *         &lt;element name="media" type="{}media_type" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "media"
        })
        public static class XhtmlR
            extends XhtmlRType
        {

            protected MediaType media;

            /**
             * Gets the value of the media property.
             * 
             * @return
             *     possible object is
             *     {@link MediaType }
             *     
             */
            public MediaType getMedia() {
                return media;
            }

            /**
             * Sets the value of the media property.
             * 
             * @param value
             *     allowed object is
             *     {@link MediaType }
             *     
             */
            public void setMedia(MediaType value) {
                this.media = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="media_reference" type="{}media_reference_type"/>
     *         &lt;element name="media_alternative_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mediaReference",
        "mediaAlternativeText"
    })
    public static class HdMedia {

        @XmlElement(name = "media_reference", required = true)
        protected String mediaReference;
        @XmlElement(name = "media_alternative_text")
        protected String mediaAlternativeText;

        /**
         * Gets the value of the mediaReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMediaReference() {
            return mediaReference;
        }

        /**
         * Sets the value of the mediaReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMediaReference(String value) {
            this.mediaReference = value;
        }

        /**
         * Gets the value of the mediaAlternativeText property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMediaAlternativeText() {
            return mediaAlternativeText;
        }

        /**
         * Sets the value of the mediaAlternativeText property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMediaAlternativeText(String value) {
            this.mediaAlternativeText = value;
        }

    }

}
