//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for heading_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="heading_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}short_title"/>
 *         &lt;element ref="{}long_title"/>
 *         &lt;element name="abstract">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="xhtml_r">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{}xhtml_r_type">
 *                           &lt;sequence>
 *                             &lt;element name="media" type="{}media_type" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}media"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "heading_type", propOrder = {
    "shortTitle",
    "longTitle",
    "_abstract",
    "media"
})
public class HeadingType {

    @XmlElement(name = "short_title", required = true)
    protected String shortTitle;
    @XmlElement(name = "long_title", required = true)
    protected String longTitle;
    @XmlElement(name = "abstract", required = true)
    protected HeadingType.Abstract _abstract;
    @XmlElement(required = true)
    protected Media media;

    /**
     * Gets the value of the shortTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShortTitle() {
        return shortTitle;
    }

    /**
     * Sets the value of the shortTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShortTitle(String value) {
        this.shortTitle = value;
    }

    /**
     * Gets the value of the longTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLongTitle() {
        return longTitle;
    }

    /**
     * Sets the value of the longTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLongTitle(String value) {
        this.longTitle = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link HeadingType.Abstract }
     *     
     */
    public HeadingType.Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeadingType.Abstract }
     *     
     */
    public void setAbstract(HeadingType.Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the media property.
     * 
     * @return
     *     possible object is
     *     {@link Media }
     *     
     */
    public Media getMedia() {
        return media;
    }

    /**
     * Sets the value of the media property.
     * 
     * @param value
     *     allowed object is
     *     {@link Media }
     *     
     */
    public void setMedia(Media value) {
        this.media = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="xhtml_r">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{}xhtml_r_type">
     *                 &lt;sequence>
     *                   &lt;element name="media" type="{}media_type" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "xhtmlR"
    })
    public static class Abstract {

        @XmlElement(name = "xhtml_r", required = true)
        protected HeadingType.Abstract.XhtmlR xhtmlR;

        /**
         * Gets the value of the xhtmlR property.
         * 
         * @return
         *     possible object is
         *     {@link HeadingType.Abstract.XhtmlR }
         *     
         */
        public HeadingType.Abstract.XhtmlR getXhtmlR() {
            return xhtmlR;
        }

        /**
         * Sets the value of the xhtmlR property.
         * 
         * @param value
         *     allowed object is
         *     {@link HeadingType.Abstract.XhtmlR }
         *     
         */
        public void setXhtmlR(HeadingType.Abstract.XhtmlR value) {
            this.xhtmlR = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{}xhtml_r_type">
         *       &lt;sequence>
         *         &lt;element name="media" type="{}media_type" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "media"
        })
        public static class XhtmlR
            extends XhtmlRType
        {

            protected MediaType media;

            /**
             * Gets the value of the media property.
             * 
             * @return
             *     possible object is
             *     {@link MediaType }
             *     
             */
            public MediaType getMedia() {
                return media;
            }

            /**
             * Sets the value of the media property.
             * 
             * @param value
             *     allowed object is
             *     {@link MediaType }
             *     
             */
            public void setMedia(MediaType value) {
                this.media = value;
            }

        }

    }

}
