//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * 
 *       "Inline" covers inline or "text-level" element
 *       -- simplified to a verbatim list of allowed elements --
 *       
 * 
 * <p>Java class for Inline complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Inline">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;group ref="{}inline"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Inline", propOrder = {
    "content"
})
@XmlSeeAlso({
    Sub.class,
    Strong.class,
    Em.class,
    Sup.class,
    Strike.class,
    S.class,
    U.class,
    B.class,
    I.class,
    Tt.class,
    Span.class
})
public class Inline {

    @XmlElementRefs({
        @XmlElementRef(name = "tt", type = Tt.class),
        @XmlElementRef(name = "a", type = A.class),
        @XmlElementRef(name = "b", type = B.class),
        @XmlElementRef(name = "em", type = Em.class),
        @XmlElementRef(name = "i", type = I.class),
        @XmlElementRef(name = "u", type = U.class),
        @XmlElementRef(name = "sup", type = Sup.class),
        @XmlElementRef(name = "strike", type = Strike.class),
        @XmlElementRef(name = "strong", type = Strong.class),
        @XmlElementRef(name = "span", type = Span.class),
        @XmlElementRef(name = "br", type = Br.class),
        @XmlElementRef(name = "sub", type = Sub.class),
        @XmlElementRef(name = "s", type = S.class)
    })
    @XmlMixed
    protected List<Object> content;

    /**
     * 
     *       "Inline" covers inline or "text-level" element
     *       -- simplified to a verbatim list of allowed elements --
     *       Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Tt }
     * {@link A }
     * {@link String }
     * {@link B }
     * {@link Em }
     * {@link I }
     * {@link U }
     * {@link Sup }
     * {@link Strike }
     * {@link Strong }
     * {@link Span }
     * {@link Br }
     * {@link Sub }
     * {@link S }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

}
