//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for ipg_meta_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ipg_meta_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="ipg_reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipg_title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipg_creator" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="ipg_language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipg_document_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipg_classification" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="ipg_description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipg_keywords" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ipg_meta_type", propOrder = {
    "ipgReferenceOrIpgTitleOrIpgCreator"
})
public class IpgMetaType {

    @XmlElementRefs({
        @XmlElementRef(name = "ipg_description", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_title", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_reference", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_creator", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_language", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_keywords", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_classification", type = JAXBElement.class),
        @XmlElementRef(name = "ipg_document_type", type = JAXBElement.class)
    })
    protected List<JAXBElement<String>> ipgReferenceOrIpgTitleOrIpgCreator;

    /**
     * Gets the value of the ipgReferenceOrIpgTitleOrIpgCreator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ipgReferenceOrIpgTitleOrIpgCreator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIpgReferenceOrIpgTitleOrIpgCreator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<String>> getIpgReferenceOrIpgTitleOrIpgCreator() {
        if (ipgReferenceOrIpgTitleOrIpgCreator == null) {
            ipgReferenceOrIpgTitleOrIpgCreator = new ArrayList<JAXBElement<String>>();
        }
        return this.ipgReferenceOrIpgTitleOrIpgCreator;
    }

}
