//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="media_reference" type="{}media_reference_type"/>
 *         &lt;element name="media_alternative_text" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mediaReference",
    "mediaAlternativeText"
})
@XmlRootElement(name = "media")
public class Media {

    @XmlElement(name = "media_reference", required = true)
    protected String mediaReference;
    @XmlElement(name = "media_alternative_text")
    protected String mediaAlternativeText;

    /**
     * Gets the value of the mediaReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaReference() {
        return mediaReference;
    }

    /**
     * Sets the value of the mediaReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaReference(String value) {
        this.mediaReference = value;
    }

    /**
     * Gets the value of the mediaAlternativeText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaAlternativeText() {
        return mediaAlternativeText;
    }

    /**
     * Sets the value of the mediaAlternativeText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaAlternativeText(String value) {
        this.mediaAlternativeText = value;
    }

}
