//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;


import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the eu.europa.ec.etrustex.tools.translation.jaxb package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Abstract_QNAME = new QName("", "abstract");
    private final static QName _ShortTitle_QNAME = new QName("", "short_title");
    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _Staging_QNAME = new QName("", "staging");
    private final static QName _LongTitle_QNAME = new QName("", "long_title");
    private final static QName _RObjectId_QNAME = new QName("", "r_object_id");
    private final static QName _Medias_QNAME = new QName("", "medias");
    private final static QName _Active_QNAME = new QName("", "active");
    private final static QName _Wip_QNAME = new QName("", "wip");
    private final static QName _ContentR_QNAME = new QName("", "content_r");
    private final static QName _Links_QNAME = new QName("", "links");
    private final static QName _IpgMetaTypeIpgReference_QNAME = new QName("", "ipg_reference");
    private final static QName _IpgMetaTypeIpgLanguage_QNAME = new QName("", "ipg_language");
    private final static QName _IpgMetaTypeIpgClassification_QNAME = new QName("", "ipg_classification");
    private final static QName _IpgMetaTypeIpgDocumentType_QNAME = new QName("", "ipg_document_type");
    private final static QName _IpgMetaTypeIpgTitle_QNAME = new QName("", "ipg_title");
    private final static QName _IpgMetaTypeIpgKeywords_QNAME = new QName("", "ipg_keywords");
    private final static QName _IpgMetaTypeIpgDescription_QNAME = new QName("", "ipg_description");
    private final static QName _IpgMetaTypeIpgCreator_QNAME = new QName("", "ipg_creator");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: eu.europa.ec.etrustex.tools.translation.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MediaRType }
     * 
     */
    public MediaRType createMediaRType() {
        return new MediaRType();
    }

    /**
     * Create an instance of {@link Tt }
     * 
     */
    public Tt createTt() {
        return new Tt();
    }

    /**
     * Create an instance of {@link Inline }
     * 
     */
    public Inline createInline() {
        return new Inline();
    }

    /**
     * Create an instance of {@link A }
     * 
     */
    public A createA() {
        return new A();
    }

    /**
     * Create an instance of {@link ContentRefType.RefLinks }
     * 
     */
    public ContentRefType.RefLinks createContentRefTypeRefLinks() {
        return new ContentRefType.RefLinks();
    }

    /**
     * Create an instance of {@link MediaType }
     * 
     */
    public MediaType createMediaType() {
        return new MediaType();
    }

    /**
     * Create an instance of {@link IpgMetaType }
     * 
     */
    public IpgMetaType createIpgMetaType() {
        return new IpgMetaType();
    }

    /**
     * Create an instance of {@link Em }
     * 
     */
    public Em createEm() {
        return new Em();
    }

    /**
     * Create an instance of {@link HdHeadingType.HdAbstract.XhtmlR }
     * 
     */
    public HdHeadingType.HdAbstract.XhtmlR createHdHeadingTypeHdAbstractXhtmlR() {
        return new HdHeadingType.HdAbstract.XhtmlR();
    }

    /**
     * Create an instance of {@link LanguageDescriptor }
     * 
     */
    public LanguageDescriptor createLanguageDescriptor() {
        return new LanguageDescriptor();
    }

    /**
     * Create an instance of {@link LinkRListType }
     * 
     */
    public LinkRListType createLinkRListType() {
        return new LinkRListType();
    }

    /**
     * Create an instance of {@link HdHeadingType.HdAbstract }
     * 
     */
    public HdHeadingType.HdAbstract createHdHeadingTypeHdAbstract() {
        return new HdHeadingType.HdAbstract();
    }

    /**
     * Create an instance of {@link RenditionUrl }
     * 
     */
    public RenditionUrl createRenditionUrl() {
        return new RenditionUrl();
    }

    /**
     * Create an instance of {@link Media }
     * 
     */
    public Media createMedia() {
        return new Media();
    }

    /**
     * Create an instance of {@link Span }
     * 
     */
    public Span createSpan() {
        return new Span();
    }

    /**
     * Create an instance of {@link ContentRefType }
     * 
     */
    public ContentRefType createContentRefType() {
        return new ContentRefType();
    }

    /**
     * Create an instance of {@link Div }
     * 
     */
    public Div createDiv() {
        return new Div();
    }

    /**
     * Create an instance of {@link HeadingType }
     * 
     */
    public HeadingType createHeadingType() {
        return new HeadingType();
    }

    /**
     * Create an instance of {@link HdHeadingType.HdMedia }
     * 
     */
    public HdHeadingType.HdMedia createHdHeadingTypeHdMedia() {
        return new HdHeadingType.HdMedia();
    }

    /**
     * Create an instance of {@link ShortContent }
     * 
     */
    public ShortContent createShortContent() {
        return new ShortContent();
    }

    /**
     * Create an instance of {@link HdHeadingType }
     * 
     */
    public HdHeadingType createHdHeadingType() {
        return new HdHeadingType();
    }

    /**
     * Create an instance of {@link AContent }
     * 
     */
    public AContent createAContent() {
        return new AContent();
    }

    /**
     * Create an instance of {@link XhtmlFragmentType }
     * 
     */
    public XhtmlFragmentType createXhtmlFragmentType() {
        return new XhtmlFragmentType();
    }

    /**
     * Create an instance of {@link ContentQual.ContentLifeCycle }
     * 
     */
    public ContentQual.ContentLifeCycle createContentQualContentLifeCycle() {
        return new ContentQual.ContentLifeCycle();
    }

    /**
     * Create an instance of {@link S }
     * 
     */
    public S createS() {
        return new S();
    }

    /**
     * Create an instance of {@link AbstractType }
     * 
     */
    public AbstractType createAbstractType() {
        return new AbstractType();
    }

    /**
     * Create an instance of {@link ContentQual.ContentCategoryR }
     * 
     */
    public ContentQual.ContentCategoryR createContentQualContentCategoryR() {
        return new ContentQual.ContentCategoryR();
    }

    /**
     * Create an instance of {@link UrlType }
     * 
     */
    public UrlType createUrlType() {
        return new UrlType();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link U }
     * 
     */
    public U createU() {
        return new U();
    }

    /**
     * Create an instance of {@link HeadingType.Abstract }
     * 
     */
    public HeadingType.Abstract createHeadingTypeAbstract() {
        return new HeadingType.Abstract();
    }

    /**
     * Create an instance of {@link ContentQual }
     * 
     */
    public ContentQual createContentQual() {
        return new ContentQual();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link Strike }
     * 
     */
    public Strike createStrike() {
        return new Strike();
    }

    /**
     * Create an instance of {@link Strong }
     * 
     */
    public Strong createStrong() {
        return new Strong();
    }

    /**
     * Create an instance of {@link eu.europa.ec.etrustex.tools.translation.jaxb.MediaRListType }
     * 
     */
    public MediaRListType createMediaRListType() {
        return new MediaRListType();
    }

    /**
     * Create an instance of {@link LinkRType }
     * 
     */
    public LinkRType createLinkRType() {
        return new LinkRType();
    }

    /**
     * Create an instance of {@link HeadingType.Abstract.XhtmlR }
     * 
     */
    public HeadingType.Abstract.XhtmlR createHeadingTypeAbstractXhtmlR() {
        return new HeadingType.Abstract.XhtmlR();
    }

    /**
     * Create an instance of {@link Br }
     * 
     */
    public Br createBr() {
        return new Br();
    }

    /**
     * Create an instance of {@link XhtmlRType }
     * 
     */
    public XhtmlRType createXhtmlRType() {
        return new XhtmlRType();
    }

    /**
     * Create an instance of {@link CwcmsMetadata }
     * 
     */
    public CwcmsMetadata createCwcmsMetadata() {
        return new CwcmsMetadata();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "abstract")
    public JAXBElement<AbstractType> createAbstract(AbstractType value) {
        return new JAXBElement<AbstractType>(_Abstract_QNAME, AbstractType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "short_title")
    public JAXBElement<String> createShortTitle(String value) {
        return new JAXBElement<String>(_ShortTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<TextType> createText(TextType value) {
        return new JAXBElement<TextType>(_Text_QNAME, TextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "staging")
    public JAXBElement<String> createStaging(String value) {
        return new JAXBElement<String>(_Staging_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "long_title")
    public JAXBElement<String> createLongTitle(String value) {
        return new JAXBElement<String>(_LongTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "r_object_id")
    public JAXBElement<String> createRObjectId(String value) {
        return new JAXBElement<String>(_RObjectId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MediaRListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "medias")
    public JAXBElement<MediaRListType> createMedias(MediaRListType value) {
        return new JAXBElement<MediaRListType>(_Medias_QNAME, MediaRListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "active")
    public JAXBElement<String> createActive(String value) {
        return new JAXBElement<String>(_Active_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "wip")
    public JAXBElement<String> createWip(String value) {
        return new JAXBElement<String>(_Wip_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XhtmlRType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "content_r")
    public JAXBElement<XhtmlRType> createContentR(XhtmlRType value) {
        return new JAXBElement<XhtmlRType>(_ContentR_QNAME, XhtmlRType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkRListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "links")
    public JAXBElement<LinkRListType> createLinks(LinkRListType value) {
        return new JAXBElement<LinkRListType>(_Links_QNAME, LinkRListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_reference", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgReference(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgReference_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_language", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgLanguage(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgLanguage_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_classification", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgClassification(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgClassification_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_document_type", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgDocumentType(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgDocumentType_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_title", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgTitle(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgTitle_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_keywords", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgKeywords(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgKeywords_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_description", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgDescription(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgDescription_QNAME, String.class, IpgMetaType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ipg_creator", scope = IpgMetaType.class)
    public JAXBElement<String> createIpgMetaTypeIpgCreator(String value) {
        return new JAXBElement<String>(_IpgMetaTypeIpgCreator_QNAME, String.class, IpgMetaType.class, value);
    }

}
