//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{}wip"/>
 *         &lt;element ref="{}staging" minOccurs="0"/>
 *         &lt;element ref="{}active" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "rendition_url")
public class RenditionUrl {

    @XmlElement(required = true)
    protected String wip;
    protected String staging;
    protected String active;

    /**
     * Gets the value of the wip property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWip() {
        return wip;
    }

    /**
     * Sets the value of the wip property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWip(String value) {
        this.wip = value;
    }

    /**
     * Gets the value of the staging property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStaging() {
        return staging;
    }

    /**
     * Sets the value of the staging property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStaging(String value) {
        this.staging = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActive(String value) {
        this.active = value;
    }

}
