//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.23 at 11:21:10 AM CEST 
//


package eu.europa.ec.etrustex.tools.translation.jaxb;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for xhtml_r_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xhtml_r_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xhtml_fragment" type="{}xhtml_fragment_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml_r_type", propOrder = {
    "xhtmlFragment"
})
@XmlSeeAlso({
    eu.europa.ec.etrustex.tools.translation.jaxb.HdHeadingType.HdAbstract.XhtmlR.class,
    eu.europa.ec.etrustex.tools.translation.jaxb.HeadingType.Abstract.XhtmlR.class
})
public class XhtmlRType {

    @XmlElement(name = "xhtml_fragment", required = true)
    protected XhtmlFragmentType xhtmlFragment;

    /**
     * Gets the value of the xhtmlFragment property.
     * 
     * @return
     *     possible object is
     *     {@link XhtmlFragmentType }
     *     
     */
    public XhtmlFragmentType getXhtmlFragment() {
        return xhtmlFragment;
    }

    /**
     * Sets the value of the xhtmlFragment property.
     * 
     * @param value
     *     allowed object is
     *     {@link XhtmlFragmentType }
     *     
     */
    public void setXhtmlFragment(XhtmlFragmentType value) {
        this.xhtmlFragment = value;
    }

}
