update ETX_WEB_PARTY set PAR_EMAIL = trim(PAR_EMAIL)
where PAR_EMAIL is not null and PAR_EMAIL != trim(PAR_EMAIL);

update ETX_WEB_PARTY set PAR_STS_NOTIF_EMAIL = trim(PAR_STS_NOTIF_EMAIL)
where PAR_STS_NOTIF_EMAIL is not null and PAR_STS_NOTIF_EMAIL != trim(PAR_STS_NOTIF_EMAIL);

update ETX_WEB_BUSINESS_USER_CONFIG set BUC_EMAIL = trim(BUC_EMAIL)
where BUC_EMAIL is not null and BUC_EMAIL != trim(BUC_EMAIL);

update ETX_WEB_BUSINESS_USER_CONFIG set BUC_STS_NOTIF_EMAIL = trim(BUC_STS_NOTIF_EMAIL)
where BUC_STS_NOTIF_EMAIL is not null and BUC_STS_NOTIF_EMAIL != trim(BUC_STS_NOTIF_EMAIL);
