-- Alter Party
ALTER TABLE ETX_WEB_PARTY ADD (PAR_WEB_MANAGED NUMBER(1) NULL)
/
UPDATE ETX_WEB_PARTY SET PAR_WEB_MANAGED = 1
/
ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_WEB_MANAGED NOT NULL)
/
ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_NODE_USR NULL)
/
ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_NODE_PASS NULL)
/
ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_NOTIFICATIONS_ENABLED NULL)
/
ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_CONSUME_NODE_MSG NULL)
/
ALTER TABLE ETX_WEB_PARTY MODIFY (PAR_STS_NOTIF_ENABLED NULL)
/
ALTER TABLE ETX_WEB_PARTY DROP UNIQUE (PAR_NODE_NAME)
/
ALTER TABLE ETX_WEB_PARTY ADD CONSTRAINT UNIQUE_NODE_NAME_BUS_ID UNIQUE(PAR_NODE_NAME, BUS_ID)
/

-- Alter Party ICA
ALTER TABLE ETX_WEB_PARTY_ICA ADD (REMOTE_PAR_ID NUMBER(19))
/
ALTER TABLE ETX_WEB_PARTY_ICA ADD CONSTRAINT FK_PCA_REMOTE_PAR_ID FOREIGN KEY (REMOTE_PAR_ID) REFERENCES ETX_WEB_PARTY (PAR_ID)
/

-- Data Migration
DECLARE
  CURSOR icas_cursor IS
  SELECT pi.PCA_ID id, pi.PCA_NODE_NAME node_name, pi.PCA_DISPLAY_NAME display_name, p.BUS_ID bus_id, pi.PCA_STATE active_state
  FROM ETX_WEB_PARTY_ICA pi JOIN ETX_WEB_PARTY p
  ON pi.PAR_ID = p.PAR_ID
  WHERE pi.PCA_STATE = 1;

  row_ica icas_cursor%ROWTYPE;
  remote_party_id NUMBER(19);
BEGIN
  FOR row_ica IN icas_cursor
  LOOP
    BEGIN
      SELECT par_id into remote_party_id from ETX_WEB_PARTY where PAR_NODE_NAME = row_ica.node_name and BUS_ID = row_ica.bus_id;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
      -- Insert new remote parties if they don't exist in the ETX_WEB_PARTY already
      remote_party_id := ETX_WEB_PRTSEQ.nextval;
      INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_NODE_NAME, PAR_DISPLAY_NAME, BUS_ID, PAR_CREATED_BY, PAR_ACTIVE_STATE, PAR_WEB_MANAGED)
      VALUES (remote_party_id, row_ica.node_name, row_ica.display_name, row_ica.bus_id, 0, 1, 0);
    END;
    UPDATE ETX_WEB_PARTY_ICA SET REMOTE_PAR_ID = remote_party_id WHERE PCA_ID = row_ica.id;
  END LOOP;
END;
/

-- Alter Party ICA
ALTER TABLE ETX_WEB_PARTY_ICA MODIFY (REMOTE_PAR_ID NOT NULL)
/
ALTER TABLE ETX_WEB_PARTY_ICA DROP COLUMN PCA_NODE_NAME
/
ALTER TABLE ETX_WEB_PARTY_ICA DROP COLUMN PCA_DISPLAY_NAME
/