-- ========================================
-- Sets environment-dependent DB parameters
-- environment: TEST
-- ========================================
-- SYSTEMS
INSERT INTO ETX_WEB_SYSTEM (SYS_ID, SYS_USERNAME, SYS_PASSWORD, SYS_COMMENT)
VALUES (1, 'e-TrustExWeb', 'e-TrustExWeb', 'eTrustEx Web platform')
/

-- PARTIES
INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (1,null,'EDMA','EDMA-APP-PARTY','EDMA-APP-PARTY', 1, 0, null)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (2,'ARRANDA-PARTY@europa.eu','DG-COMP','ARRANDA-PARTY','ARRANDA-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (3,'KHAMIRA-PARTY@europa.eu','DG-COMP','KHAMIRA-PARTY','KHAMIRA-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (4,'JUGANCO-PARTY@europa.eu','DG-COMP','JUGANCO-PARTY','JUGANCO-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (5,'SCHOTCN-PARTY@europa.eu','DG-COMP','SCHOTCN-PARTY','SCHOTCN-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (6,'ATIENRO-PARTY@europa.eu','DG-COMP','ATIENRO-PARTY','ATIENRO-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (7,'EDMA-PARTY1@europa.eu','EDMA','EDMA-PARTY1','EDMA-PARTY1', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (8,'ETXW-NP-PARTY1@europa.eu','NP','ETXW-NP-PARTY1','ETXW-NP-PARTY1', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (9,'ETXW-NP-PARTY2@europa.eu','NP','ETXW-NP-PARTY2','ETXW-NP-PARTY2', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (10,'ETXW-NP-PARTY3@europa.eu','NP','ETXW-NP-PARTY3','ETXW-NP-PARTY3', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (11,'ETXW-PARTY10@europa.eu','NP','ETXW-PARTY10','ETXW-PARTY10', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (12,'ETXW-PARTY11@europa.eu','NP','ETXW-PARTY11','ETXW-PARTY11', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (13,'CHOLAAR-PARTY@europa.eu','DIGIT','CHOLAAR-PARTY','CHOLAAR-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (14,'apladas@gmail.com','Greece','TOLIS-EDMA-APP-PARTY','TOLIS-EDMA-APP-PARTY', 1, 0, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (15,'EGREFFE-PARTY1@europa.eu','E-GREFFE','EGREFFE-PARTY1','EGREFFE-PARTY1', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (16, null,'E-GREFFE','EGREFFE-APP-PARTY','EGREFFE-APP-PARTY', 0, 1, null)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (17,'TEST1-EGREFFE-WEB-PARTY@europa.eu','E-GREFFE','TEST1-EGREFFE-WEB-PARTY','TEST1-EGREFFE-WEB-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (18,'TEST2-EGREFFE-WEB-PARTY@europa.eu','E-GREFFE','TEST2-EGREFFE-WEB-PARTY','TEST2-EGREFFE-WEB-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (19,'TEST3-EGREFFE-WEB-PARTY@europa.eu','E-GREFFE','TEST3-EGREFFE-WEB-PARTY','TEST3-EGREFFE-WEB-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (20,'DEV-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV-EGREFFE-APP-PARTY','DEV-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (21,'apladas@gmail.com','Greece','TOLIS-EGREFFE-APP-PARTY','TOLIS-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (22,'DEV1-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV1-EGREFFE-APP-PARTY','DEV1-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (23,'DEV2-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV2-EGREFFE-APP-PARTY','DEV2-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (24,'DEV3-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV3-EGREFFE-APP-PARTY','DEV3-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (25,'DEV4-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV4-EGREFFE-APP-PARTY','DEV4-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (26,'DEV5-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV5-EGREFFE-APP-PARTY','DEV5-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (27,'DEV6-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV6-EGREFFE-APP-PARTY','DEV6-EGREFFE-APP-PARTY', 0, 1, 1)
/

INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_EMAIL, PAR_INSTITUTION, PAR_NAME, PAR_REF_ID, PAR_CAN_SEND, PAR_STANDARD_VIEW, SYS_ID)
VALUES (28,'DEV7-EGREFFE-APP-PARTY@europa.eu','DEV_E-GREFFE','DEV7-EGREFFE-APP-PARTY','DEV7-EGREFFE-APP-PARTY', 0, 1, 1)
/


-- USERS
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'apladap','Tolis',17)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'lietaju','Julien Lietard',19)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'lairdth','LAIR-DUEE Thomas (COMP-EXT)',6)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'bertogd','BERTON Geraud',13)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'cochuje','COCHU Jean-Pierre (COMP)',6)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'stigtla','STIGTER Laurie (COMP-EXT)',6)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'tenapju','TENA PAGAN Juan',13)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'micleva','Valer Micle',2)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'atienro','ATIENZA Roberto (COMP)',6)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'khamira','KHAMIDOV Ravshan (COMP-EXT)',3)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'cholaar','CHOLAKIAN Armen L (DIGIT-EXT)',3)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'burlefr','BURLET Frederic',3)
/
Insert into ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,PAR_ID) values (ETX_WEB_USRSEQ.nextval'lesouju','Julien Lesouef',18)
/

-- CONFIG
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (1,'application_url','https://webgate.test.ec.europa.eu/e-trustex/')
/
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (2,'etrustex.doc.wrapper.service.uri','https://webgate.test.ec.europa.eu/e-trustexnode/DocumentWrapper-2.0')
/
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (3,'etrustex.doc.bundle.service.uri','https://webgate.test.ec.europa.eu/e-trustexnode/DocumentBundle-2.0')
/
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (4,'etrustex.doc.agreement.service.uri','https://webgate.test.ec.europa.eu/e-trustexnode/RetrieveInterchangeAgreementsRequest-2.0')
/
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (5,'edma.app.party','EDMA-APP-PARTY')
/
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (6,'etrustex.doc.wrapper.service.internal.uri','https://wltdig03.cc.cec.eu.int:1122/etrustex/external/DocumentWrapper-2.0')
/
INSERT INTO ETX_WEB_CONFIG (CFG_ID,CFG_PROP_NAME,CFG_PROP_VALUE) values (7,'etx.node.services.RetrieveRequestService.uri','https://webgate.test.ec.europa.eu/e-trustexnode/RetrieveRequest-2.0')
/




