-- ========================================
-- Sets environment-dependent DB parameters
-- environment: LOCAL PC rudokka
-- ========================================

-- USERS
INSERT INTO ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,USR_CREATED_BY, USR_CREATED_ON, USR_ACTIVE_STATE)
VALUES (ETX_WEB_USRSEQ.nextval,'micleva','Valer Micle', ETX_WEB_USRSEQ.currval, sysdate, 1)
/
INSERT INTO ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,USR_CREATED_BY, USR_CREATED_ON, USR_ACTIVE_STATE)
VALUES (ETX_WEB_USRSEQ.nextval,'lambept','Peter Lamber', ETX_WEB_USRSEQ.currval, sysdate, 1)
/
INSERT INTO ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,USR_CREATED_BY, USR_CREATED_ON, USR_ACTIVE_STATE)
VALUES (ETX_WEB_USRSEQ.nextval,'cholaar','Armen Cholakian', ETX_WEB_USRSEQ.currval, sysdate, 1)
/
INSERT INTO ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,USR_CREATED_BY, USR_CREATED_ON, USR_ACTIVE_STATE)
VALUES (ETX_WEB_USRSEQ.nextval,'lubiesz','Szymon Lubieniecki', ETX_WEB_USRSEQ.currval, sysdate, 1)
/
INSERT INTO ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,USR_CREATED_BY, USR_CREATED_ON, USR_ACTIVE_STATE)
VALUES (ETX_WEB_USRSEQ.nextval,'cabalen','Enrique Cabal', ETX_WEB_USRSEQ.currval, sysdate, 1)
/
INSERT INTO ETX_WEB_USER (USR_ID,USR_LOGIN,USR_NAME,USR_CREATED_BY, USR_CREATED_ON, USR_ACTIVE_STATE)
VALUES (ETX_WEB_USRSEQ.nextval,'canofcr','Cristiano Canofari', ETX_WEB_USRSEQ.currval, sysdate, 1)
/

-- BUSINESSES
INSERT INTO ETX_WEB_BUSINESS (BUS_ID, BUS_NAME, BUS_DESCRIPTION, BUS_CREATED_BY, BUS_CREATED_ON, BUS_ACTIVE_STATE)
VALUES (ETX_WEB_BUSSEQ.nextval,'EDMA', null, ETX_WEB_USRSEQ.currval, sysdate, 1)
/

-- PARTIES
INSERT INTO ETX_WEB_PARTY (PAR_ID, PAR_NODE_NAME, PAR_NODE_USR, PAR_NODE_PASS, PAR_DISPLAY_NAME, BUS_ID, PAR_NOTIFICATIONS_ENABLED, PAR_CREATED_BY, PAR_CREATED_ON, PAR_ACTIVE_STATE, PAR_STS_NOTIF_ENABLED)
VALUES (ETX_WEB_PRTSEQ.nextval,'DEV-ETX-ALEX-PARTY','e-TrustExWeb','e-TrustExWeb','DEV-ETX-ALEX-PARTY',ETX_WEB_BUSSEQ.currval,0, ETX_WEB_USRSEQ.currval, sysdate, 1, 0)
/

-- PARTY_ROLES
INSERT INTO ETX_WEB_USER_ROLE (URO_ID,USR_ID,ROL_TYPE, URO_CREATED_BY, URO_CREATED_ON, URO_ACTIVE_STATE)
VALUES (ETX_WEB_UROSEQ.nextval, ETX_WEB_USRSEQ.currval,'SYSTEM_ADMIN',ETX_WEB_USRSEQ.currval,SYSDATE, 1)
/

INSERT INTO ETX_WEB_USER_ROLE (URO_ID,USR_ID,ROL_TYPE, URO_CREATED_BY, URO_CREATED_ON, URO_ACTIVE_STATE)
VALUES (ETX_WEB_UROSEQ.nextval, ETX_WEB_USRSEQ.currval - 1,'SYSTEM_ADMIN',ETX_WEB_USRSEQ.currval,SYSDATE, 1)
/

INSERT INTO ETX_WEB_USER_ROLE (URO_ID,USR_ID,ROL_TYPE, URO_CREATED_BY, URO_CREATED_ON, URO_ACTIVE_STATE)
VALUES (ETX_WEB_UROSEQ.nextval, ETX_WEB_USRSEQ.currval - 2,'SYSTEM_ADMIN',ETX_WEB_USRSEQ.currval,SYSDATE, 1)
/

INSERT INTO ETX_WEB_USER_ROLE (URO_ID,USR_ID,ROL_TYPE, URO_CREATED_BY, URO_CREATED_ON, URO_ACTIVE_STATE)
VALUES (ETX_WEB_UROSEQ.nextval, ETX_WEB_USRSEQ.currval - 3,'SYSTEM_ADMIN',ETX_WEB_USRSEQ.currval,SYSDATE, 1)
/

INSERT INTO ETX_WEB_USER_ROLE (URO_ID,USR_ID,ROL_TYPE, URO_CREATED_BY, URO_CREATED_ON, URO_ACTIVE_STATE)
VALUES (ETX_WEB_UROSEQ.nextval, ETX_WEB_USRSEQ.currval - 4,'SYSTEM_ADMIN',ETX_WEB_USRSEQ.currval,SYSDATE, 1)
/

INSERT INTO ETX_WEB_USER_ROLE (URO_ID,USR_ID,ROL_TYPE, URO_CREATED_BY, URO_CREATED_ON, URO_ACTIVE_STATE)
VALUES (ETX_WEB_UROSEQ.nextval, ETX_WEB_USRSEQ.currval - 5,'SYSTEM_ADMIN',ETX_WEB_USRSEQ.currval,SYSDATE, 1)
/

-- BUSINESS_CONFIGS
INSERT INTO ETX_WEB_BUSINESS_CONFIG (BCG_ID, BUS_ID, BCG_PROPERTY_NAME, BCG_PROPERTY_VALUE)
VALUES (ETX_WEB_BCGSEQ.nextval, ETX_WEB_BUSSEQ.currval, 'etx.business.warn.email.notif.enabled', 'true')
/

INSERT INTO ETX_WEB_BUSINESS_CONFIG (BCG_ID, BUS_ID, BCG_PROPERTY_NAME, BCG_PROPERTY_VALUE)
VALUES (ETX_WEB_BCGSEQ.nextval, ETX_WEB_BUSSEQ.currval, 'etx.business.custom.view.name', 'edma')
/

INSERT INTO ETX_WEB_BUSINESS_CONFIG (BCG_ID, BUS_ID, BCG_PROPERTY_NAME, BCG_PROPERTY_VALUE)
VALUES (ETX_WEB_BCGSEQ.nextval, ETX_WEB_BUSSEQ.currval, 'etx.business.receiver.node.party.name', 'DEV_EDMA_APP_PARTY')
/

INSERT INTO ETX_WEB_BUSINESS_CONFIG (BCG_ID, BUS_ID, BCG_PROPERTY_NAME, BCG_PROPERTY_VALUE)
VALUES (ETX_WEB_BCGSEQ.nextval, ETX_WEB_BUSSEQ.currval,'etx.business.sending.enabled','true')
/